-- Variables initialization
-- init some local variables
_var = {
	client = {},
	menu = {},
	menus = {},
	settings = {},
	editor = {},
	freecam = {},
	map = {},
	maps = {},
	loader = {},
	props = {},
	peds = {},
	vehicles = {},
	instructionnal = {},
}
_var.client.hasAccess = false
_var.instructionnal.buttons = nil
_var.instructionnal.signature = nil
_var.menus.editor = {
	isOpened = false,
	closedFrame = 0,
	bannerTexture = nil,
	objects = {
		main = nil,
		mainMaps = nil,
		mainMetadata = nil,
		mainSettings = nil,
	},
}
_var.menus.spawn = {
	isOpened = false,
	current = nil,
	objects = {
		objects = nil,
		peds = nil,
		vehicles = nil,
	},
}
_var.menu.pedsFilter = ""
_var.menu.vehiclesFilter = ""
_var.menu.cameraSpeedArrayIndex = Config.Settings.CameraSpeedIndex
_var.menu.cameraSpeedArray = {
	_("camera_speed_very_slow"),
	_("camera_speed_slow"),
	_("camera_speed_normal"),
	_("camera_speed_fast"),
	_("camera_speed_very_fast"),
}
_var.settings.showRadar = Config.Settings.ShowRadar
_var.settings.showXYZAxis = Config.Settings.ShowXYZAxis
_var.settings.show3DCursor = Config.Settings.Show3DCursor
_var.settings.cameraSpeed = (2 * (_var.menu.cameraSpeedArrayIndex - 1) / (#_var.menu.cameraSpeedArray - 1)) + 0.05
_var.settings.showInstructionalButtons = Config.Settings.ShowInstructionalButtons
_var.settings.showInfoBars = Config.Settings.ShowInfoBars
_var.settings.showSelectionMarker = Config.Settings.ShowSelectionMarker
_var.settings.showBoundingBox = Config.Settings.ShowBoundingBox
_var.settings.relativeTranslation = Config.Settings.RelativeTranslation
_var.settings.networkObjects = Config.Settings.NetworkObjects
_var.editor.states = {
	inactive = "inactive",
	flying = "flying",
	adding = "adding",
	selected = "selected",
}
_var.editor.state = _var.editor.states.inactive
_var.editor.rotationModes = { "pitch", "roll", "yaw" }
_var.editor.rotationModeIndex = 3
_var.editor.selected = nil
_var.editor.cursorPosition = vector3(0.0, 0.0, 0.0)
_var.editor.cursorProp = nil
_var.editor.cursorModel = "prop_mp_placement"
_var.editor.ray = { hit = false, entity = 0, surfaceNormal = vector3(0.0, 0.0, 0.0) }
_var.editor.controlsNames = {
	[19] = "INPUT_CHARACTER_WHEEL",
	[21] = "INPUT_SPRINT",
	[22] = "INPUT_JUMP",
	[24] = "INPUT_ATTACK",
	[25] = "INPUT_AIM",
	[26] = "INPUT_LOOK_BEHIND",
	[45] = "INPUT_RELOAD",
	[51] = "INPUT_CONTEXT",
	[63] = "INPUT_VEH_MOVE_LEFT_ONLY",
	[64] = "INPUT_VEH_MOVE_RIGHT_ONLY",
	[71] = "INPUT_VEH_ACCELERATE",
	[72] = "INPUT_VEH_BRAKE",
	[73] = "INPUT_VEH_DUCK",
	[75] = "INPUT_VEH_EXIT",
	[85] = "INPUT_VEH_RADIO_WHEEL",
	[132] = "INPUT_VEH_SUB_DESCEND",
	[157] = "INPUT_SELECT_WEAPON_UNARMED",
	[158] = "INPUT_SELECT_WEAPON_MELEE",
	[160] = "INPUT_SELECT_WEAPON_SHOTGUN",
	[166] = "INPUT_SELECT_CHARACTER_MICHAEL",
	[167] = "INPUT_SELECT_CHARACTER_FRANKLIN",
	[168] = "INPUT_SELECT_CHARACTER_TREVOR",
	[172] = "INPUT_CELLPHONE_UP",
	[173] = "INPUT_CELLPHONE_DOWN",
	[174] = "INPUT_CELLPHONE_LEFT",
	[175] = "INPUT_CELLPHONE_RIGHT",
	[176] = "INPUT_CELLPHONE_SELECT",
	[200] = "INPUT_FRONTEND_PAUSE_ALTERNATE",
	[256] = "INPUT_CREATOR_DELETE",
}
_var.freecam.cam = nil
_var.freecam.isPaused = false
_var.freecam.forwardVector = vector3(0.0, 1.0, 0.0)
_var.freecam.mouseSensitivity = 5.0
_var.map.current = nil
_var.map.loadRequestId = 0
_var.maps.list = {}
_var.loader.maps = {}
_var.loader.nextId = 1
_var.props.categoryArrayIndex = 1
_var.props.typeArrayIndex = 1
_var.props.colorArrayIndex = 1
_var.props.coloredCategory = "FMMC_PLIB_19"
_var.props.coloredCategoryColors = 5
_var.props.colorsByModel = {}
_var.peds.isLoaded = false
_var.peds.models = {}
_var.vehicles.isLoaded = false
_var.vehicles.models = {}
_var.props.categories = {
	{
		name = "MC_PRSTNT_T0",
		props = {
			{ model = "stt_prop_track_start", label = "MC_PR_STNT59" },
			{ model = "stt_prop_track_start_02", label = "MC_PR_STNT2" },
			{ model = "stt_prop_race_start_line_01", label = "MC_PR_STNT190" },
			{ model = "stt_prop_race_start_line_01b", label = "MC_PR_STNT190b" },
			{ model = "stt_prop_race_start_line_02", label = "MC_PR_STNT191" },
			{ model = "stt_prop_race_start_line_03", label = "MC_PR_STNT192" },
			{ model = "stt_prop_race_start_line_02b", label = "MC_PR_STNT243" },
			{ model = "stt_prop_race_start_line_03b", label = "MC_PR_STNT244" },
			{ model = "stt_prop_track_straight_s", label = "MC_PR_STNT105" },
			{ model = "stt_prop_track_straight_m", label = "MC_PR_STNT50" },
			{ model = "stt_prop_track_straight_lm", label = "MC_PR_STNT51a" },
			{ model = "stt_prop_track_straight_l", label = "MC_PR_STNT51" },
			{ model = "stt_prop_track_bend_m", label = "MC_PR_STNT48" },
			{ model = "stt_prop_track_bend_l", label = "MC_PR_STNT239" },
			{ model = "stt_prop_track_bend_l_b", label = "MC_PR_STNT49" },
			{ model = "stt_prop_track_bend2_l", label = "MC_PR_STNT240" },
			{ model = "stt_prop_track_bend2_l_b", label = "MC_PR_STNT141" },
			{ model = "stt_prop_track_bend_5d", label = "MC_PR_STNT222" },
			{ model = "stt_prop_track_bend_15d", label = "MC_PR_STNT223" },
			{ model = "stt_prop_track_bend_30d", label = "MC_PR_STNT224" },
			{ model = "stt_prop_track_bend_180d", label = "MC_PR_STNT225" },
			{ model = "stt_prop_track_fork", label = "MC_PR_STNT137" },
			{ model = "stt_prop_track_cross", label = "MC_PR_STNT56" },
			{ model = "stt_prop_track_straight_bar_s", label = "MC_PR_STNT106" },
			{ model = "stt_prop_track_straight_bar_m", label = "MC_PR_STNT54" },
			{ model = "stt_prop_track_straight_lm_bar", label = "MC_PR_STNT55a" },
			{ model = "stt_prop_track_straight_bar_l", label = "MC_PR_STNT55" },
			{ model = "stt_prop_track_bend_bar_m", label = "MC_PR_STNT52" },
			{ model = "stt_prop_track_bend_bar_l", label = "MC_PR_STNT241" },
			{ model = "stt_prop_track_bend_bar_l_b", label = "MC_PR_STNT53" },
			{ model = "stt_prop_track_bend2_bar_l", label = "MC_PR_STNT259" },
			{ model = "stt_prop_track_bend2_bar_l_b", label = "MC_PR_STNT142" },
			{ model = "stt_prop_track_bend_5D_bar", label = "MC_PR_STNT264" },
			{ model = "stt_prop_track_bend_15D_bar", label = "MC_PR_STNT265" },
			{ model = "stt_prop_track_bend_30D_bar", label = "MC_PR_STNT266" },
			{ model = "stt_Prop_track_bend_180D_bar", label = "MC_PR_STNT267" },
			{ model = "stt_prop_track_fork_bar", label = "MC_PR_STNT138" },
			{ model = "stt_prop_track_cross_bar", label = "MC_PR_STNT57" },
			{ model = "stt_prop_track_funnel", label = "MC_PR_STNT58" },
			{ model = "stt_prop_track_funnel_ads_01a", label = "MC_PR_STNT235" },
			{ model = "stt_prop_track_funnel_ads_01b", label = "MC_PR_STNT253" },
			{ model = "stt_prop_track_funnel_ads_01c", label = "MC_PR_STNT254" },
			{ model = "stt_prop_track_link", label = "MC_PR_STNT115" },
			{ model = "stt_prop_track_chicane_L", label = "MC_PR_STNT167" },
			{ model = "stt_prop_track_chicane_L_02", label = "MC_PR_STNT196" },
			{ model = "stt_prop_track_chicane_R", label = "MC_PR_STNT168" },
			{ model = "stt_prop_track_chicane_R_02", label = "MC_PR_STNT197" },
			{ model = "stt_prop_track_block_01", label = "MC_PR_STNT236" },
			{ model = "stt_prop_track_block_02", label = "MC_PR_STNT237" },
			{ model = "stt_prop_track_block_03", label = "MC_PR_STNT238" },
			{ model = "sr_Prop_Track_Straight_L_D5", label = "MC_SR_PROP_31" },
			{ model = "sr_Prop_Track_Straight_L_D15", label = "MC_SR_PROP_32" },
			{ model = "sr_Prop_Track_Straight_L_D30", label = "MC_SR_PROP_33" },
			{ model = "sr_Prop_Track_Straight_L_D45", label = "MC_SR_PROP_34" },
			{ model = "sr_Prop_Track_Straight_L_U5", label = "MC_SR_PROP_35" },
			{ model = "sr_Prop_Track_Straight_L_U15", label = "MC_SR_PROP_36" },
			{ model = "sr_Prop_Track_Straight_L_U30", label = "MC_SR_PROP_37" },
			{ model = "sr_Prop_Track_Straight_L_U45", label = "MC_SR_PROP_38" },
		},
	},
	{
		name = "MC_PRSTNT_T7",
		props = {
			{ model = "stt_prop_stunt_track_start_02", label = "MC_PR_STNT1" },
			{ model = "stt_prop_stunt_track_st_02", label = "MC_PR_STNT245" },
			{ model = "stt_prop_stunt_track_start", label = "MC_PR_STNT71" },
			{ model = "stt_prop_stunt_track_st_01", label = "MC_PR_STNT246" },
			{ model = "stt_prop_stunt_track_exshort", label = "MC_PR_STNT154" },
			{ model = "stt_prop_stunt_track_short", label = "MC_PR_STNT103" },
			{ model = "stt_prop_stunt_track_straight", label = "MC_PR_STNT80" },
			{ model = "stt_prop_stunt_track_turn", label = "MC_PR_STNT73" },
			{ model = "stt_prop_stunt_track_sh15", label = "MC_PR_STNT107" },
			{ model = "stt_prop_stunt_track_sh30", label = "MC_PR_STNT108" },
			{ model = "stt_prop_stunt_track_sh45", label = "MC_PR_STNT109" },
			{ model = "stt_Prop_Stunt_Track_SH45_a", label = "MC_PR_STNT109A" },
			{ model = "stt_prop_stunt_track_uturn", label = "MC_PR_STNT81" },
			{ model = "stt_prop_stunt_track_cutout", label = "MC_PR_STNT113" },
			{ model = "stt_prop_stunt_track_otake", label = "MC_PR_STNT69" },
			{ model = "stt_prop_stunt_track_fork", label = "MC_PR_STNT139" },
			{ model = "stt_prop_stunt_track_funnel", label = "MC_PR_STNT70" },
			{ model = "stt_prop_stunt_track_funlng", label = "MC_PR_STNT140" },
			{ model = "stt_prop_stunt_track_slope15", label = "MC_PR_STNT74" },
			{ model = "stt_prop_stunt_track_slope30", label = "MC_PR_STNT75" },
			{ model = "stt_prop_stunt_track_slope45", label = "MC_PR_STNT76" },
			{ model = "stt_prop_stunt_track_hill", label = "MC_PR_STNT77" },
			{ model = "stt_prop_stunt_track_hill2", label = "MC_PR_STNT78" },
			{ model = "stt_prop_stunt_track_bumps", label = "MC_PR_STNT136" },
			{ model = "stt_prop_stunt_track_jump", label = "MC_PR_STNT79" },
			{ model = "stt_prop_stunt_jump15", label = "MC_PR_STNT116" },
			{ model = "stt_prop_stunt_jump30", label = "MC_PR_STNT117" },
			{ model = "stt_prop_stunt_jump45", label = "MC_PR_STNT118" },
			{ model = "stt_prop_stunt_track_link", label = "MC_PR_STNT114" },
			{ model = "stt_prop_stunt_track_dwlink", label = "MC_PR_STNT3" },
			{ model = "stt_prop_stunt_track_dwlink_02", label = "MC_PR_STNT247" },
			{ model = "stt_prop_stunt_track_dwshort", label = "MC_PR_STNT4" },
			{ model = "stt_prop_stunt_track_dwsh15", label = "MC_PR_STNT5" },
			{ model = "stt_prop_stunt_track_dwturn", label = "MC_PR_STNT6" },
			{ model = "stt_prop_stunt_track_dwuturn", label = "MC_PR_STNT7" },
			{ model = "stt_prop_stunt_track_dwslope15", label = "MC_PR_STNT8" },
			{ model = "stt_prop_stunt_track_dwslope30", label = "MC_PR_STNT9" },
			{ model = "stt_prop_stunt_track_dwslope45", label = "MC_PR_STNT10" },
			{ model = "stt_prop_track_tube_02", label = "MC_PR_STNT170" },
		},
	},
	{
		name = "MC_PRSTNT_T8",
		props = {
			{ model = "stt_prop_stunt_tube_xxs", label = "MC_PR_STNT104" },
			{ model = "stt_prop_stunt_tube_xs", label = "MC_PR_STNT37" },
			{ model = "stt_prop_stunt_tube_s", label = "MC_PR_STNT38" },
			{ model = "stt_prop_stunt_tube_m", label = "MC_PR_STNT39" },
			{ model = "stt_prop_stunt_tube_l", label = "MC_PR_STNT100" },
			{ model = "stt_prop_stunt_tube_crn", label = "MC_PR_STNT46" },
			{ model = "stt_prop_stunt_tube_crn_5d", label = "MC_PR_STNT226" },
			{ model = "stt_prop_stunt_tube_crn_15d", label = "MC_PR_STNT227" },
			{ model = "stt_prop_stunt_tube_crn_30d", label = "MC_PR_STNT228" },
			{ model = "stt_prop_stunt_tube_crn2", label = "MC_PR_STNT102" },
			{ model = "stt_prop_stunt_tube_fork", label = "MC_PR_STNT134" },
			{ model = "stt_prop_stunt_tube_cross", label = "MC_PR_STNT40" },
			{ model = "stt_prop_stunt_tube_gap_01", label = "MC_PR_STNT165" },
			{ model = "stt_prop_stunt_tube_gap_02", label = "MC_PR_STNT166" },
			{ model = "stt_prop_stunt_tube_gap_03", label = "MC_PR_STNT262" },
			{ model = "stt_prop_stunt_tube_qg", label = "MC_PR_STNT41" },
			{ model = "stt_prop_stunt_tube_hg", label = "MC_PR_STNT42" },
			{ model = "stt_prop_stunt_tube_jmp", label = "MC_PR_STNT44" },
			{ model = "stt_prop_stunt_tube_jmp2", label = "MC_PR_STNT82" },
			{ model = "stt_prop_stunt_tube_fn_01", label = "MC_PR_STNT83" },
			{ model = "stt_prop_stunt_tube_fn_02", label = "MC_PR_STNT84" },
			{ model = "stt_prop_stunt_tube_fn_03", label = "MC_PR_STNT85" },
			{ model = "stt_prop_stunt_tube_fn_04", label = "MC_PR_STNT86" },
			{ model = "stt_prop_stunt_tube_fn_05", label = "MC_PR_STNT87" },
			{ model = "stt_prop_stunt_tube_ent", label = "MC_PR_STNT93" },
			{ model = "stt_prop_stunt_tube_end", label = "MC_PR_STNT47" },
			{ model = "sr_prop_sr_tube_end", label = "MC_PR_STNT47b" },
			{ model = "stt_prop_stunt_tube_speed", label = "MC_PR_STNT248" },
			{ model = "sr_Prop_Spec_Tube_Refill", label = "MC_SR_PROP_44" },
			{ model = "stt_prop_track_tube_01", label = "MC_PR_STNT169" },
		},
	},
	{
		name = "FMMC_PLIB_19",
		props = {
			{ model = "sr_Prop_Spec_Tube_XXS_01a", label = "MC_SR_PROP_06" },
			{ model = "sr_Prop_stunt_Tube_XS_01a", label = "MC_SR_PROP_10" },
			{ model = "sr_Prop_Spec_Tube_S_01a", label = "MC_SR_PROP_03" },
			{ model = "sr_Prop_Spec_Tube_M_01a", label = "MC_SR_PROP_04" },
			{ model = "sr_Prop_Spec_Tube_L_01a", label = "MC_SR_PROP_05" },
			{ model = "sr_Prop_Spec_Tube_Crn_01a", label = "MC_SR_PROP_01" },
			{ model = "sr_Prop_stunt_Tube_Crn_5D_01a", label = "MC_SR_PROP_07" },
			{ model = "sr_Prop_stunt_Tube_Crn_15D_01a", label = "MC_SR_PROP_08" },
			{ model = "sr_Prop_Spec_Tube_Crn_30D_01a", label = "MC_SR_PROP_02" },
			{ model = "sr_prop_stunt_tube_crn2_01a", label = "MC_SR_PROP_09" },
		},
	},
	{
		name = "MC_PRSTNT_T4",
		props = {
			{ model = "stt_prop_stunt_jump_s", label = "MC_PR_STNT88" },
			{ model = "stt_prop_stunt_jump_m", label = "MC_PR_STNT89" },
			{ model = "stt_prop_stunt_jump_l", label = "MC_PR_STNT90" },
			{ model = "stt_prop_stunt_jump_sb", label = "MC_PR_STNT110" },
			{ model = "stt_prop_stunt_jump_mb", label = "MC_PR_STNT111" },
			{ model = "stt_prop_stunt_jump_lb", label = "MC_PR_STNT112" },
			{ model = "stt_prop_ramp_jump_xs", label = "MC_PR_STNT25" },
			{ model = "stt_prop_ramp_jump_s", label = "MC_PR_STNT26" },
			{ model = "stt_prop_ramp_jump_m", label = "MC_PR_STNT27" },
			{ model = "stt_prop_ramp_jump_l", label = "MC_PR_STNT28" },
			{ model = "stt_prop_ramp_jump_xl", label = "MC_PR_STNT29" },
			{ model = "stt_prop_ramp_jump_xxl", label = "MC_PR_STNT30" },
			{ model = "stt_prop_track_jump_01a", label = "MC_PR_STNT156" },
			{ model = "stt_prop_track_jump_01b", label = "MC_PR_STNT157" },
			{ model = "stt_prop_track_jump_01c", label = "MC_PR_STNT158" },
			{ model = "stt_prop_track_jump_02a", label = "MC_PR_STNT159" },
			{ model = "stt_prop_track_jump_02b", label = "MC_PR_STNT160" },
			{ model = "stt_prop_track_jump_02c", label = "MC_PR_STNT161" },
			{ model = "stt_prop_ramp_adj_flip_mb", label = "MC_PR_STNT32" },
			{ model = "stt_prop_ramp_adj_flip_s", label = "MC_PR_STNT193" },
			{ model = "stt_prop_ramp_adj_flip_sb", label = "MC_PR_STNT31" },
			{ model = "stt_prop_ramp_adj_flip_m", label = "MC_PR_STNT173" },
			{ model = "stt_prop_stunt_ramp", label = "MC_PR_STNT33" },
			{ model = "stt_prop_stunt_wideramp", label = "MC_PR_STNT135" },
			{ model = "stt_prop_stunt_bblock_qp3", label = "MC_PR_STNT162" },
			{ model = "imp_Prop_ImpExp_BBlock_QP3" },
			{ model = "stt_prop_stunt_bblock_qp2", label = "MC_PR_STNT163" },
			{ model = "stt_prop_stunt_bblock_qp", label = "MC_PR_STNT164" },
			{ model = "stt_prop_stunt_bblock_hump_01", label = "MC_PR_STNT163s" },
			{ model = "stt_prop_stunt_bblock_hump_02", label = "MC_PR_STNT163m" },
			{ model = "bkr_Prop_biker_BBlock_Cor_03" },
			{ model = "bkr_Prop_biker_BBlock_Cor_02" },
			{ model = "bkr_Prop_biker_BBlock_Cor" },
		},
	},
	{
		name = "MC_PRSTNT_T2",
		props = {
			{ model = "stt_prop_track_SpeedUp", label = "MC_PR_STNT132" },
			{ model = "stt_prop_track_SpeedUp_T2", label = "MC_PR_STNT232" },
			{ model = "stt_prop_track_SpeedUp_T1", label = "MC_PR_STNT231" },
			{ model = "stt_prop_track_SlowDown", label = "MC_PR_STNT133" },
			{ model = "stt_prop_track_SlowDown_T2", label = "MC_PR_STNT234" },
			{ model = "stt_prop_track_SlowDown_T1", label = "MC_PR_STNT233" },
			{ model = "sr_Prop_Track_Refill", label = "MC_SR_PROP_39" },
			{ model = "sr_Prop_Track_Refill_T2", label = "MC_SR_PROP_40" },
			{ model = "sr_Prop_Track_Refill_T1", label = "MC_SR_PROP_41" },
			{ model = "stt_prop_hoop_small_01", label = "MC_PR_STNT188" },
			{ model = "stt_prop_hoop_constraction_01a", label = "MC_PR_STNT189" },
			{ model = "stt_prop_speakerstack_01a", label = "MC_PR_STNT263" },
		},
	},
	{
		name = "MC_PRSTNT_T5",
		props = {
			{ model = "stt_prop_ramp_adj_hloop", label = "MC_PR_STNT19" },
			{ model = "stt_prop_ramp_adj_loop", label = "MC_PR_STNT20" },
			{ model = "stt_prop_ramp_multi_loop_rb", label = "MC_PR_STNT21" },
			{ model = "stt_prop_stunt_jump_loop", label = "MC_PR_STNT319" },
			{ model = "stt_prop_ramp_spiral_s", label = "MC_PR_STNT24" },
			{ model = "stt_prop_ramp_spiral_l_s", label = "MC_PR_STNT150" },
			{ model = "stt_prop_ramp_spiral_m", label = "MC_PR_STNT23" },
			{ model = "stt_prop_ramp_spiral_l_m", label = "MC_PR_STNT151" },
			{ model = "stt_prop_ramp_spiral_l", label = "MC_PR_STNT22" },
			{ model = "stt_prop_ramp_spiral_l_l", label = "MC_PR_STNT152" },
			{ model = "stt_prop_ramp_spiral_xxl", label = "MC_PR_STNT155" },
			{ model = "stt_prop_ramp_spiral_l_xxl", label = "MC_PR_STNT153" },
			{ model = "stt_prop_wallride_45r", label = "MC_PR_STNT143" },
			{ model = "stt_prop_wallride_45ra", label = "MC_PR_STNT249" },
			{ model = "stt_prop_wallride_45l", label = "MC_PR_STNT144" },
			{ model = "stt_prop_wallride_45la", label = "MC_PR_STNT250" },
			{ model = "stt_prop_wallride_90r", label = "MC_PR_STNT145" },
			{ model = "stt_prop_wallride_90rb", label = "MC_PR_STNT251" },
			{ model = "stt_prop_wallride_90l", label = "MC_PR_STNT146" },
			{ model = "stt_prop_wallride_90lb", label = "MC_PR_STNT252" },
			{ model = "stt_prop_wallride_04", label = "MC_PR_STNT60" },
			{ model = "stt_prop_wallride_01", label = "MC_PR_STNT256" },
			{ model = "stt_prop_wallride_01b", label = "MC_PR_STNT91" },
			{ model = "stt_prop_wallride_05", label = "MC_PR_STNT258" },
			{ model = "stt_prop_wallride_05b", label = "MC_PR_STNT61" },
			{ model = "stt_prop_wallride_02", label = "MC_PR_STNT257" },
			{ model = "stt_prop_wallride_02b", label = "MC_PR_STNT92" },
			{ model = "stt_prop_stunt_bowlpin_stand", label = "MC_PR_STNT64" },
			{ model = "stt_prop_stunt_soccer_goal", label = "MC_PR_STNT67" },
			{ model = "stt_prop_stunt_landing_zone_01", label = "MC_PR_STNT171" },
			{ model = "stt_prop_hoop_tyre_01a", label = "MC_PR_STNT194" },
			{ model = "sr_Prop_SR_Track_JumpWall", label = "MC_SR_PROP_42" },
		},
	},
	{
		name = "MC_PRSTNT_T3",
		props = {
			{ model = "stt_prop_stunt_bblock_sml1", label = "MC_PR_STNT120" },
			{ model = "stt_prop_stunt_bblock_sml2", label = "MC_PR_STNT121" },
			{ model = "stt_prop_stunt_bblock_sml3", label = "MC_PR_STNT122" },
			{ model = "stt_prop_stunt_bblock_mdm1", label = "MC_PR_STNT123" },
			{ model = "stt_prop_stunt_bblock_mdm2", label = "MC_PR_STNT124" },
			{ model = "stt_prop_stunt_bblock_mdm3", label = "MC_PR_STNT125" },
			{ model = "stt_prop_stunt_bblock_lrg1", label = "MC_PR_STNT126" },
			{ model = "stt_prop_stunt_bblock_lrg2", label = "MC_PR_STNT127" },
			{ model = "stt_prop_stunt_bblock_lrg3", label = "MC_PR_STNT128" },
			{ model = "stt_prop_stunt_bblock_xl1", label = "MC_PR_STNT129" },
			{ model = "stt_prop_stunt_bblock_xl2", label = "MC_PR_STNT130" },
			{ model = "stt_prop_stunt_bblock_xl3", label = "MC_PR_STNT131" },
			{ model = "stt_prop_stunt_bblock_huge_01", label = "MC_PR_STNT147" },
			{ model = "stt_prop_stunt_bblock_huge_02", label = "MC_PR_STNT148" },
			{ model = "stt_prop_stunt_bblock_huge_03", label = "MC_PR_STNT149" },
			{ model = "stt_prop_stunt_bblock_huge_04", label = "MC_PR_STNT229" },
			{ model = "stt_prop_stunt_bblock_huge_05", label = "MC_PR_STNT230" },
			{ model = "imp_Prop_ImpExp_BBlock_Huge_01" },
			{ model = "imp_Prop_ImpExp_BBlock_Sml1" },
			{ model = "imp_Prop_ImpExp_BBlock_Mdm1" },
			{ model = "imp_Prop_ImpExp_BBlock_Lrg1" },
			{ model = "imp_Prop_ImpExp_BBlock_XL1" },
		},
	},
	{
		name = "FMMC_PLIB_20",
		props = {
			{ model = "sr_Prop_Special_BBlock_Sml1", label = "MC_SR_PROP_49" },
			{ model = "sr_Prop_Special_BBlock_Mdm1", label = "MC_SR_PROP_50" },
			{ model = "sr_Prop_Special_BBlock_Lrg11", label = "MC_SR_PROP_51" },
			{ model = "sr_Prop_Special_BBlock_XL1", label = "MC_SR_PROP_52" },
			{ model = "sr_Prop_Special_BBlock_Sml2", label = "MC_SR_PROP_53" },
			{ model = "sr_Prop_Special_BBlock_Mdm2", label = "MC_SR_PROP_54" },
			{ model = "sr_Prop_Special_BBlock_Lrg2", label = "MC_SR_PROP_55" },
			{ model = "sr_Prop_Special_BBlock_XL2", label = "MC_SR_PROP_56" },
			{ model = "sr_Prop_Special_BBlock_Sml3", label = "MC_SR_PROP_57" },
			{ model = "sr_Prop_Special_BBlock_Mdm3", label = "MC_SR_PROP_58" },
			{ model = "sr_Prop_Special_BBlock_Lrg3", label = "MC_SR_PROP_59" },
			{ model = "sr_Prop_Special_BBlock_XL3_Fixed", label = "MC_SR_PROP_60" },
		},
	},
	{
		name = "FMMC_PLIB_21",
		props = {
			{ model = "stt_prop_stunt_target", label = "MC_PR_STNT34" },
			{ model = "stt_prop_stunt_target_small", label = "MC_PR_STNT320" },
			{ model = "gr_prop_gr_target_1_01a", label = "MC_SR_PROP_61" },
			{ model = "gr_prop_gr_target_1_01b", label = "MC_SR_PROP_61b" },
			{ model = "gr_prop_gr_target_2_04a", label = "MC_SR_PROP_62" },
			{ model = "gr_prop_gr_target_2_04b", label = "MC_SR_PROP_62b" },
			{ model = "gr_prop_gr_target_3_03a", label = "MC_SR_PROP_63" },
			{ model = "gr_prop_gr_target_3_03b", label = "MC_SR_PROP_63b" },
			{ model = "gr_prop_gr_target_4_01a", label = "MC_SR_PROP_64" },
			{ model = "gr_prop_gr_target_4_01b", label = "MC_SR_PROP_64b" },
			{ model = "gr_prop_gr_target_5_01a", label = "MC_SR_PROP_65" },
			{ model = "gr_prop_gr_target_5_01b", label = "MC_SR_PROP_65b" },
			{ model = "gr_prop_gr_target_small_01a", label = "MC_SR_PROP_68" },
			{ model = "gr_prop_gr_target_small_01b", label = "MC_SR_PROP_68b" },
			{ model = "gr_prop_gr_target_small_03a", label = "MC_SR_PROP_72" },
			{ model = "gr_prop_gr_target_small_02a", label = "MC_SR_PROP_73" },
			{ model = "gr_prop_gr_target_small_06a", label = "MC_SR_PROP_75" },
			{ model = "gr_prop_gr_target_small_07a", label = "MC_SR_PROP_76" },
			{ model = "gr_prop_gr_target_small_04a", label = "MC_SR_PROP_74" },
			{ model = "gr_prop_gr_target_small_05a", label = "MC_SR_PROP_69" },
			{ model = "gr_prop_gr_target_long_01a", label = "MC_SR_PROP_67" },
			{ model = "gr_prop_gr_target_large_01a", label = "MC_SR_PROP_66" },
			{ model = "gr_prop_gr_target_large_01b", label = "MC_SR_PROP_66b" },
			{ model = "gr_prop_gr_target_trap_01a", label = "MC_SR_PROP_70" },
			{ model = "gr_prop_gr_target_trap_02a", label = "MC_SR_PROP_71" },
		},
	},
	{
		name = "MC_PRSTNT_T6",
		props = {
			{ model = "stt_prop_track_stop_sign", label = "MC_PR_STNT101" },
			{ model = "stt_prop_corner_sign_01", label = "MC_PR_STNT174" },
			{ model = "stt_prop_corner_sign_02", label = "MC_PR_STNT175" },
			{ model = "stt_prop_corner_sign_03", label = "MC_PR_STNT176" },
			{ model = "stt_prop_corner_sign_04", label = "MC_PR_STNT177" },
			{ model = "stt_prop_corner_sign_05", label = "MC_PR_STNT178" },
			{ model = "stt_prop_corner_sign_06", label = "MC_PR_STNT179" },
			{ model = "stt_prop_corner_sign_07", label = "MC_PR_STNT180" },
			{ model = "stt_prop_corner_sign_08", label = "MC_PR_STNT181" },
			{ model = "stt_prop_corner_sign_09", label = "MC_PR_STNT182" },
			{ model = "stt_prop_corner_sign_10", label = "MC_PR_STNT183" },
			{ model = "stt_prop_corner_sign_11", label = "MC_PR_STNT184" },
			{ model = "stt_prop_corner_sign_12", label = "MC_PR_STNT185" },
			{ model = "stt_prop_corner_sign_13", label = "MC_PR_STNT186" },
			{ model = "stt_prop_corner_sign_14", label = "MC_PR_STNT187" },
			{ model = "stt_prop_sign_circuit_01", label = "MC_PR_STNT198" },
			{ model = "stt_prop_sign_circuit_02", label = "MC_PR_STNT199" },
			{ model = "stt_prop_sign_circuit_03", label = "MC_PR_STNT200" },
			{ model = "stt_prop_sign_circuit_05", label = "MC_PR_STNT202" },
			{ model = "stt_prop_sign_circuit_04", label = "MC_PR_STNT201" },
			{ model = "stt_prop_sign_circuit_06", label = "MC_PR_STNT203" },
			{ model = "stt_prop_sign_circuit_07", label = "MC_PR_STNT204" },
			{ model = "stt_prop_sign_circuit_08", label = "MC_PR_STNT205" },
			{ model = "stt_prop_sign_circuit_09", label = "MC_PR_STNT206" },
			{ model = "stt_prop_sign_circuit_10", label = "MC_PR_STNT207" },
			{ model = "stt_prop_sign_circuit_11", label = "MC_PR_STNT208" },
			{ model = "stt_prop_sign_circuit_12", label = "MC_PR_STNT209" },
			{ model = "stt_prop_sign_circuit_13", label = "MC_PR_STNT210" },
			{ model = "stt_prop_sign_circuit_14", label = "MC_PR_STNT211" },
			{ model = "stt_prop_sign_circuit_15", label = "MC_PR_STNT212" },
			{ model = "stt_prop_tyre_wall_01", label = "MC_PR_STNT213" },
			{ model = "stt_prop_tyre_wall_02", label = "MC_PR_STNT214" },
			{ model = "stt_prop_tyre_wall_03", label = "MC_PR_STNT215" },
			{ model = "stt_prop_tyre_wall_04", label = "MC_PR_STNT274" },
			{ model = "stt_prop_tyre_wall_05", label = "MC_PR_STNT275" },
			{ model = "stt_prop_tyre_wall_06", label = "MC_PR_STNT276" },
			{ model = "stt_prop_tyre_wall_07", label = "MC_PR_STNT277" },
			{ model = "stt_prop_tyre_wall_08", label = "MC_PR_STNT278" },
			{ model = "stt_prop_tyre_wall_09", label = "MC_PR_STNT279" },
			{ model = "stt_prop_tyre_wall_010", label = "MC_PR_STNT280" },
			{ model = "stt_prop_tyre_wall_011", label = "MC_PR_STNT281" },
			{ model = "stt_prop_tyre_wall_012", label = "MC_PR_STNT282" },
			{ model = "stt_prop_tyre_wall_013", label = "MC_PR_STNT283" },
			{ model = "stt_prop_tyre_wall_014", label = "MC_PR_STNT316" },
			{ model = "stt_prop_tyre_wall_015", label = "MC_PR_STNT284" },
			{ model = "stt_prop_tyre_wall_0r1", label = "MC_PR_STNT216" },
			{ model = "stt_prop_tyre_wall_0r2", label = "MC_PR_STNT217" },
			{ model = "stt_prop_tyre_wall_0r06", label = "MC_PR_STNT285" },
			{ model = "stt_prop_tyre_wall_0r07", label = "MC_PR_STNT286" },
			{ model = "stt_prop_tyre_wall_0r011", label = "MC_PR_STNT287" },
			{ model = "stt_prop_tyre_wall_0r012", label = "MC_PR_STNT288" },
			{ model = "stt_prop_tyre_wall_0r013", label = "MC_PR_STNT289" },
			{ model = "stt_prop_tyre_wall_0r014", label = "MC_PR_STNT290" },
			{ model = "stt_prop_tyre_wall_0r019", label = "MC_PR_STNT291" },
			{ model = "stt_prop_tyre_wall_0r3", label = "MC_PR_STNT218" },
			{ model = "stt_prop_tyre_wall_0r04", label = "MC_PR_STNT292" },
			{ model = "stt_prop_tyre_wall_0r05", label = "MC_PR_STNT293" },
			{ model = "stt_prop_tyre_wall_0r08", label = "MC_PR_STNT294" },
			{ model = "stt_prop_tyre_wall_0r09", label = "MC_PR_STNT295" },
			{ model = "stt_prop_tyre_wall_0r010", label = "MC_PR_STNT296" },
			{ model = "stt_prop_tyre_wall_0r015", label = "MC_PR_STNT297" },
			{ model = "stt_prop_tyre_wall_0r016", label = "MC_PR_STNT298" },
			{ model = "stt_prop_tyre_wall_0r017", label = "MC_PR_STNT299" },
			{ model = "stt_prop_tyre_wall_0r018", label = "MC_PR_STNT300" },
			{ model = "stt_prop_tyre_wall_0l1", label = "MC_PR_STNT219" },
			{ model = "stt_prop_tyre_wall_0l2", label = "MC_PR_STNT220" },
			{ model = "stt_prop_tyre_wall_0l06", label = "MC_PR_STNT301" },
			{ model = "stt_prop_tyre_wall_0l07", label = "MC_PR_STNT302" },
			{ model = "stt_prop_tyre_wall_0l013", label = "MC_PR_STNT303" },
			{ model = "stt_prop_tyre_wall_0l014", label = "MC_PR_STNT304" },
			{ model = "stt_prop_tyre_wall_0l015", label = "MC_PR_STNT305" },
			{ model = "stt_prop_tyre_wall_0l020", label = "MC_PR_STNT306" },
			{ model = "stt_prop_tyre_wall_0l3", label = "MC_PR_STNT221" },
			{ model = "stt_prop_tyre_wall_0l04", label = "MC_PR_STNT307" },
			{ model = "stt_prop_tyre_wall_0l05", label = "MC_PR_STNT308" },
			{ model = "stt_prop_tyre_wall_0l08", label = "MC_PR_STNT309" },
			{ model = "stt_prop_tyre_wall_0l010", label = "MC_PR_STNT310" },
			{ model = "stt_prop_tyre_wall_0l012", label = "MC_PR_STNT311" },
			{ model = "stt_prop_tyre_wall_0l16", label = "MC_PR_STNT312" },
			{ model = "stt_prop_tyre_wall_0l17", label = "MC_PR_STNT313" },
			{ model = "stt_prop_tyre_wall_0l018", label = "MC_PR_STNT314" },
			{ model = "stt_prop_tyre_wall_0l019", label = "MC_PR_STNT315" },
			{ model = "stt_prop_race_gantry_01", label = "MC_PR_STNT242" },
			{ model = "sr_mp_Spec_Races_Blimp_Sign", label = "MC_SR_PROP_45" },
			{ model = "sr_Mp_Spec_Races_Take_Flight_Sign", label = "MC_SR_PROP_46" },
			{ model = "sr_Mp_Spec_Races_Ron_Sign", label = "MC_SR_PROP_47" },
			{ model = "sr_Mp_Spec_Races_Xero_Sign", label = "MC_SR_PROP_48" },
		},
	},
	{
		name = "FMMC_PLIB_0",
		props = {
			{ model = "prop_const_fence02b", label = "FMMC_PR_0" },
			{ model = "prop_offroad_bale03", label = "FMMC_PR_1" },
			{ model = "prop_offroad_bale02", label = "FMMC_PR_2" },
			{ model = "prop_offroad_bale01", label = "FMMC_PR_3" },
			{ model = "prop_offroad_tyres01", label = "FMMC_PR_4" },
			{ model = "prop_offroad_tyres02", label = "FMMC_PR_5" },
			{ model = "prop_barier_conc_02a", label = "FMMC_PR_6" },
			{ model = "prop_barier_conc_05c", label = "FMMC_PR_7" },
			{ model = "prop_barier_conc_05a", label = "FMMC_PR_8" },
			{ model = "prop_barier_conc_05b", label = "FMMC_PR_9" },
			{ model = "prop_barier_conc_01a", label = "FMMC_PR_10" },
			{ model = "prop_barrier_work05", label = "FMMC_PR_PBARR" },
			{ model = "prop_fnclink_03gate5", label = "FMMC_PR_FNCMGTS" },
			{ model = "prop_fnclink_02gate3", label = "FMMC_PR_FNCMGTD" },
			{ model = "prop_air_blastfence_01", label = "FMMC_PR_FNCBLST" },
			{ model = "prop_mb_sandblock_01", label = "FMMC_PR_SNDBKSI" },
			{ model = "prop_mb_sandblock_02", label = "FMMC_PR_SNDBKTR" },
			{ model = "prop_mb_sandblock_05_cr", label = "FMMC_PR_SNDBKED" },
			{ model = "prop_mb_sandblock_04", label = "FMMC_PR_SNDBKCR" },
			{ model = "prop_mb_sandblock_03_cr", label = "FMMC_PR_SNDBKST" },
			{ model = "prop_mb_hesco_06", label = "FMMC_PR_SNDBKFT" },
			{ model = "prop_plas_barier_01a", label = "FMMC_PR_BARPRED" },
			{ model = "prop_barier_conc_02b", label = "FMMC_PR_BARCANW" },
			{ model = "prop_barrier_work06a", label = "FMMC_PR_BARWRKP" },
			{ model = "prop_barrier_work04a", label = "FMMC_PR_BARWRKW" },
			{ model = "prop_fnclink_06a", label = "FMMC_PR_FNCBWSG" },
			{ model = "prop_fnclink_06b", label = "FMMC_PR_FNCBWLN" },
			{ model = "prop_fnclink_06c", label = "FMMC_PR_FNCBWWD" },
			{ model = "prop_fnclink_06d", label = "FMMC_PR_FNCBWWL" },
			{ model = "prop_fnccorgm_03a", label = "FMMC_PR_FNCCDCF" },
			{ model = "prop_fnccorgm_03b", label = "FMMC_PR_FNCCPDF" },
			{ model = "prop_fnccorgm_03c", label = "FMMC_PR_FNCCSCF" },
			{ model = "prop_fnccorgm_02a", label = "FMMC_PR_FNCCRDF" },
			{ model = "prop_fnccorgm_02b", label = "FMMC_PR_FNCCPRF" },
			{ model = "prop_fnccorgm_02c", label = "FMMC_PR_FNCCBPF" },
			{ model = "prop_fnccorgm_02d", label = "FMMC_PR_FNCCTCF" },
			{ model = "prop_fnccorgm_02e", label = "FMMC_PR_FNCCSRF" },
			{ model = "prop_const_fence03a_cr", label = "FMMC_PR_BARWDQU" },
			{ model = "prop_const_fence03b_cr", label = "FMMC_PR_BARQADB" },
			{ model = "prop_const_fence02a", label = "FMMC_PR_BARDUBU" },
			{ model = "prop_const_fence01b_cr", label = "FMMC_PR_BARSYSTEM" },
			{ model = "prop_fncwood_16b", label = "FMMC_PR_FNCPKOD" },
			{ model = "prop_fncwood_16c", label = "FMMC_PR_FNCPKOS" },
			{ model = "prop_fnc_farm_01b", label = "FMMC_PR_FNCFMS" },
			{ model = "prop_fnc_farm_01c", label = "FMMC_PR_FNCFMSL" },
			{ model = "prop_fnc_farm_01d", label = "FMMC_PR_FNCFMD" },
			{ model = "prop_fnc_farm_01e", label = "FMMC_PR_FNCFMT" },
			{ model = "prop_fnc_farm_01f", label = "FMMC_PR_FNCFMSX" },
			{ model = "prop_hayb_st_01_cr", label = "FMMC_PR_HBSTK" },
			{ model = "prop_haybale_03", label = "FMMC_PR_HBRND" },
			{ model = "prop_haybale_02", label = "FMMC_PR_HBSSTK" },
			{ model = "prop_haybale_01", label = "FMMC_PR_HBSML" },
			{ model = "prop_offroad_tyres01", label = "FMMC_PR_4" },
			{ model = "prop_offroad_tyres02", label = "FMMC_PR_5" },
			{ model = "prop_tyre_wall_01", label = "FMMC_PR_TYR1" },
			{ model = "prop_tyre_wall_02", label = "FMMC_PR_TYR2" },
			{ model = "prop_tyre_wall_03", label = "FMMC_PR_TYR3" },
			{ model = "prop_tyre_wall_04", label = "FMMC_PR_TYR4" },
			{ model = "prop_tyre_wall_05", label = "FMMC_PR_TYR5" },
			{ model = "prop_start_gate_01" },
			{ model = "prop_beachf_01_cr", label = "FMMC_PR_BEAF" },
			{ model = "prop_sec_gate_01d", label = "FMMC_PR_98" },
			{ model = "prop_vault_shutter", label = "FMMC_PR_100" },
		},
	},
	{
		name = "FMMC_PLIB_1",
		props = {
			{ model = "prop_bench_05", label = "FMMC_PR_12" },
			{ model = "prop_bench_07", label = "FMMC_PR_13" },
			{ model = "prop_bench_01a", label = "FMMC_PR_14" },
			{ model = "prop_bench_08", label = "FMMC_PR_BNBLUE" },
			{ model = "prop_bleachers_04_cr", label = "FMMC_PR_SBLE" },
			{ model = "prop_bleachers_05_cr", label = "FMMC_PR_BLEA" },
		},
	},
	{
		name = "FMMC_PLIB_3",
		props = {
			{ model = "prop_elecbox_24", label = "FMMC_PR_17" },
			{ model = "prop_elecbox_24b", label = "FMMC_PR_18" },
			{ model = "prop_portacabin01", label = "FMMC_PR_19" },
			{ model = "prop_air_monhut_03_cr", label = "FMMC_PR_CABAPHT" },
			{ model = "prop_air_sechut_01", label = "FMMC_PR_CABSCHT" },
			{ model = "prop_tollbooth_1", label = "FMMC_PR_CABTBTH" },
			{ model = "prop_parking_hut_2", label = "FMMC_PR_CABPHUT" },
			{ model = "prop_makeup_trail_02_cr", label = "FMMC_PR_MUTR" },
			{ model = "prop_makeup_trail_01_cr", label = "FMMC_PR_SMTR" },
		},
	},
	{
		name = "FMMC_PLIB_4",
		props = {
			{ model = "prop_cementbags01", label = "FMMC_PR_20" },
			{ model = "prop_conc_blocks01a", label = "FMMC_PR_21" },
			{ model = "prop_cons_crate", label = "FMMC_PR_22" },
			{ model = "prop_jyard_block_01a", label = "FMMC_PR_23" },
			{ model = "prop_conc_sacks_02a", label = "FMMC_PR_24" },
			{ model = "prop_byard_sleeper01", label = "FMMC_PR_25" },
			{ model = "prop_shuttering01", label = "FMMC_PR_26" },
			{ model = "prop_shuttering02", label = "FMMC_PR_27" },
			{ model = "prop_shuttering03", label = "FMMC_PR_28" },
			{ model = "prop_shuttering04", label = "FMMC_PR_29" },
			{ model = "prop_woodpile_01a", label = "FMMC_PR_30" },
			{ model = "prop_woodpile_01b", label = "FMMC_PR_WODPLSM" },
			{ model = "prop_woodpile_01c", label = "FMMC_PR_31" },
			{ model = "prop_woodpile_03a", label = "FMMC_PR_WODPLUT" },
			{ model = "prop_conc_blocks01c", label = "FMMC_PR_CONCCND" },
			{ model = "prop_cons_cements01", label = "FMMC_PR_CONCSAK" },
			{ model = "prop_pipes_conc_01", label = "FMMC_PR_CNPPE" },
			{ model = "gr_prop_gr_bunkeddoor", label = "MC_GR_BNKR_DR" },
			{ model = "prop_worklight_01a", label = "FMMC_PR_WKLGHT1a" },
			{ model = "prop_worklight_02a", label = "FMMC_PR_WKLGHT2a" },
			{ model = "prop_worklight_03a", label = "FMMC_PR_WKLGHT3a" },
			{ model = "prop_worklight_03b", label = "FMMC_PR_WKLGHT3b" },
			{ model = "prop_worklight_04b", label = "FMMC_PR_WKLGHT4b" },
			{ model = "prop_worklight_04d", label = "FMMC_PR_WKLGHT4d" },
			{ model = "prop_ind_coalcar_02", label = "FMMC_PR_COALCAR" },
		},
	},
	{
		name = "FMMC_PLIB_5",
		props = {
			{ model = "prop_rub_cont_01b", label = "FMMC_PR_32" },
			{ model = "prop_rail_boxcar4", label = "FMMC_PR_33" },
			{ model = "prop_rub_railwreck_2", label = "FMMC_PR_34" },
			{ model = "prop_contr_03b_ld", label = "FMMC_PR_35" },
			{ model = "prop_container_ld2", label = "FMMC_PR_36" },
			{ model = "prop_rail_boxcar", label = "FMMC_PR_37" },
			{ model = "prop_rail_boxcar3", label = "FMMC_PR_38" },
			{ model = "prop_container_01mb", label = "FMMC_PR_CNTLNGG" },
			{ model = "prop_container_03mb", label = "FMMC_PR_CNTSHTG" },
		},
	},
	{
		name = "FMMC_PLIB_6",
		props = {
			{ model = "prop_byard_floatpile", label = "FMMC_PR_39" },
			{ model = "prop_boxpile_07a", label = "FMMC_PR_40" },
			{ model = "prop_watercrate_01", label = "FMMC_PR_41" },
			{ model = "prop_box_wood01a", label = "FMMC_PR_42" },
			{ model = "prop_box_wood03a", label = "FMMC_PR_43" },
			{ model = "prop_box_wood04a", label = "FMMC_PR_44" },
			{ model = "prop_cash_crate_01", label = "FMMC_PR_45" },
			{ model = "prop_mb_cargo_03a", label = "FMMC_PR_CRG01" },
			{ model = "prop_mb_cargo_04a", label = "FMMC_PR_CRG02" },
			{ model = "prop_air_cargo_04a", label = "FMMC_PR_CRG03" },
			{ model = "prop_mb_crate_01b", label = "FMMC_PR_CRG04" },
			{ model = "prop_mb_cargo_04a", label = "FMMC_PR_CRG02" },
			{ model = "prop_mb_cargo_04b", label = "FMMC_PR_CRG05" },
			{ model = "prop_air_cargo_01a", label = "FMMC_PR_CRGAIR" },
			{ model = "prop_mb_cargo_02a", label = "FMMC_PR_CRG06" },
			{ model = "prop_pallet_pile_02", label = "FMMC_PR_PLTPILL" },
			{ model = "prop_pallet_pile_01", label = "FMMC_PR_PLTPILS" },
			{ model = "prop_cratepile_07a", label = "FMMC_PR_CRTPILL" },
			{ model = "prop_boxpile_02b", label = "FMMC_DPR_BOXPIL" },
			{ model = "prop_boxpile_04a", label = "FMMC_PR_BOXPILW" },
			{ model = "imp_prop_impexp_boxpile_01", label = "FMMC_PR_92" },
			{ model = "hei_prop_carrier_cargo_01a" },
			{ model = "sr_prop_sr_boxpile_02", label = "FMMC_PR_111" },
			{ model = "sr_prop_sr_boxpile_03", label = "FMMC_PR_112" },
		},
	},
	{
		name = "FMMC_PLIB_7",
		props = {
			{ model = "prop_bin_13a", label = "FMMC_PR_46" },
			{ model = "prop_bin_14a", label = "FMMC_PR_47" },
			{ model = "prop_dumpster_3a", label = "FMMC_PR_48" },
			{ model = "prop_dumpster_4b", label = "FMMC_PR_49" },
			{ model = "prop_dumpster_01a", label = "FMMC_PR_50" },
			{ model = "prop_dumpster_02a", label = "FMMC_PR_DMPCLDB" },
			{ model = "prop_dumpster_02b", label = "FMMC_PR_DMPCLDM" },
			{ model = "prop_skip_06a", label = "FMMC_PR_51" },
		},
	},
	{
		name = "FMMC_PLIB_8",
		props = {
			{ model = "prop_elecbox_02a", label = "FMMC_PR_52" },
			{ model = "prop_elecbox_16", label = "FMMC_PR_53" },
			{ model = "prop_elecbox_14", label = "FMMC_PR_54" },
			{ model = "prop_elecbox_10_cr", label = "FMMC_PR_ELECBXW" },
			{ model = "prop_elecbox_15_cr", label = "FMMC_PR_ELCBXGN" },
			{ model = "prop_elecbox_17_cr", label = "FMMC_PR_ELCBXGY" },
			{ model = "prop_ind_deiseltank", label = "FMMC_PR_55" },
			{ model = "prop_ind_mech_02a", label = "FMMC_PR_56" },
			{ model = "prop_ind_mech_02b", label = "FMMC_PR_57" },
			{ model = "prop_sub_trans_01a", label = "FMMC_PR_58" },
			{ model = "prop_sub_trans_02a", label = "FMMC_PR_59" },
			{ model = "prop_sub_trans_04a", label = "FMMC_PR_60" },
			{ model = "prop_generator_03b", label = "FMMC_PR_GANDLMP" },
			{ model = "prop_feeder1_cr", label = "FMMC_PR_FEEDER" },
			{ model = "prop_set_generator_01_cr", label = "FMMC_PR_SEGE" },
		},
	},
	{
		name = "FMMC_PLIB_9",
		props = {
			{ model = "lts_prop_lts_ramp_01", label = "FMMC_PR_61" },
			{ model = "prop_skip_04", label = "FMMC_PR_62" },
			{ model = "lts_prop_lts_ramp_02", label = "FMMC_PR_63" },
			{ model = "lts_prop_lts_ramp_03", label = "FMMC_PR_64" },
			{ model = "prop_skip_08a", label = "FMMC_PR_65" },
			{ model = "prop_skip_03", label = "FMMC_PR_RMPDMPM" },
			{ model = "prop_jetski_ramp_01", label = "FMMC_PR_66" },
			{ model = "prop_byard_rampold_cr", label = "FMMC_PR_RMPOLD" },
			{ model = "prop_water_ramp_01", label = "FMMC_PR_WTRRAMP1" },
			{ model = "prop_water_ramp_02", label = "FMMC_PR_WTRRAMP2" },
			{ model = "prop_water_ramp_03", label = "FMMC_PR_WTRRAMP3" },
		},
	},
	{
		name = "FMMC_PLIB_10",
		props = {
			{ model = "prop_trafficdiv_01", label = "FMMC_PR_67" },
			{ model = "prop_sign_road_09a", label = "FMMC_PR_68" },
			{ model = "prop_sign_road_09b", label = "FMMC_PR_69" },
			{ model = "prop_sign_road_09c", label = "FMMC_PR_70" },
			{ model = "prop_sign_road_09d", label = "FMMC_PR_71" },
			{ model = "prop_sign_road_06q", label = "FMMC_PR_72" },
			{ model = "prop_sign_road_06r", label = "FMMC_PR_73" },
			{ model = "prop_sign_road_05c", label = "FMMC_PR_74" },
			{ model = "prop_sign_road_05d", label = "FMMC_PR_75" },
			{ model = "prop_sign_road_05e", label = "FMMC_PR_76" },
			{ model = "prop_sign_road_05f", label = "FMMC_PR_77" },
		},
	},
	{
		name = "FMMC_PLIB_11",
		props = {
			{ model = "prop_food_van_01", label = "FMMC_PR_78" },
			{ model = "prop_food_van_02", label = "FMMC_PR_79" },
			{ model = "prop_tanktrailer_01a", label = "FMMC_PR_80" },
			{ model = "prop_truktrailer_01a", label = "FMMC_PR_81" },
			{ model = "prop_air_stair_01", label = "FMMC_PR_STRFLY" },
			{ model = "prop_air_stair_04a_cr", label = "FMMC_PR_STRRSD" },
			{ model = "prop_air_stair_04b_cr", label = "FMMC_PR_STRLWR" },
			{ model = "prop_air_bagloader", label = "FMMC_PR_BAGLDL" },
			{ model = "prop_air_bagloader2_cr", label = "FMMC_PR_BAGLDH" },
			{ model = "prop_old_farm_03", label = "FMMC_PR_FRMOLDT" },
		},
	},
	{
		name = "FMMC_PLIB_12",
		props = {
			{ model = "prop_rub_buswreck_01", label = "FMMC_PR_82" },
			{ model = "prop_rub_buswreck_06", label = "FMMC_PR_83" },
			{ model = "prop_rub_carwreck_11", label = "FMMC_PR_84" },
			{ model = "prop_rub_carwreck_12", label = "FMMC_PR_85" },
			{ model = "prop_rub_carwreck_13", label = "FMMC_PR_86" },
			{ model = "prop_rub_carwreck_14", label = "FMMC_PR_WRKCRRD" },
			{ model = "prop_rub_carwreck_9", label = "FMMC_PR_87" },
			{ model = "prop_rub_couch02", label = "FMMC_PR_WRKCCH" },
			{ model = "prop_crashed_heli", label = "FMMC_PR_CRSHHELI" },
		},
	},
	{
		name = "FMMC_PLIB_TNR",
		props = {
			{ model = "prop_plant_group_04_cr", label = "FMMC_PR_PLNTGP" },
			{ model = "prop_bush_lrg_01c_cr", label = "FMMC_PR_BUSHLD" },
			{ model = "prop_bush_lrg_01e_cr" },
			{ model = "prop_bush_med_03_cr" },
			{ model = "prop_joshua_tree_01a", label = "FMMC_PR_JOTREE" },
			{ model = "prop_cactus_01e", label = "FMMC_PR_CACTUS" },
			{ model = "prop_log_break_01", label = "FMMC_PR_TREFLN" },
			{ model = "prop_pot_plant_05c", label = "FMMC_PR_PLNTAP" },
			{ model = "prop_pot_plant_04c", label = "FMMC_PR_PLNTPP" },
			{ model = "prop_pot_plant_05d", label = "FMMC_PR_PLNTFW" },
			{ model = "prop_pot_plant_03b" },
			{ model = "prop_pot_plant_04b", label = "FMMC_PR_PLNTTC" },
			{ model = "prop_rock_4_big2", label = "FMMC_PR_RCKBGR" },
			{ model = "prop_rock_4_c_2", label = "FMMC_PR_RCKMDF" },
			{ model = "prop_rock_4_big", label = "FMMC_PR_RCKBGF" },
			{ model = "prop_tree_olive_creator" },
			{ model = "prop_tree_eng_oak_creator" },
			{ model = "prop_tree_fallen_02", label = "FMMC_PR_NTRFLNT" },
		},
	},
	{
		name = "FMMC_PLIB_13",
		props = {
			{ model = "prop_offroad_barrel01", label = "FMMC_DPR_BARREL" },
			{ model = "prop_offroad_barrel02", label = "FMMC_DPR_BRLLNE" },
			{ model = "prop_barrel_exp_01a", label = "FMMC_DPR_EXPBRL" },
			{ model = "prop_gascyl_01a", label = "FMMC_DPR_SGC" },
			{ model = "prop_gascyl_04a", label = "FMMC_DPR_LGC" },
			{ model = "prop_gascyl_03a", label = "FMMC_DPR_TBGAS" },
			{ model = "prop_fire_exting_1b", label = "FMMC_DPR_FIREXT" },
			{ model = "prop_roadcone02c", label = "FMMC_DPR_CONE" },
			{ model = "prop_roadcone02a", label = "FMMC_DPR_TRFCNE" },
			{ model = "prop_roadcone01a", label = "FMMC_DPR_LTRFCN" },
			{ model = "prop_roadpole_01a", label = "FMMC_DPR_TRFPLE" },
			{ model = "prop_postbox_01a", label = "FMMC_DPR_MALBOX" },
			{ model = "prop_news_disp_02d", label = "FMMC_DPR_NPVND" },
			{ model = "prop_vend_water_01", label = "FMMC_DPR_WVND" },
			{ model = "prop_vend_snak_01_tu", label = "FMMC_DPR_MCHSNK" },
			{ model = "prop_train_ticket_02_tu", label = "FMMC_DPR_MCHTCK" },
			{ model = "prop_boxpile_02b", label = "FMMC_DPR_BOXPIL" },
			{ model = "prop_mc_conc_barrier_01", label = "FMMC_DPR_DESBAR" },
			{ model = "prop_fncsec_03b", label = "FMMC_DPR_SECFEN" },
			{ model = "prop_table_08_side", label = "FMMC_DPR_UPTTBL" },
			{ model = "prop_mb_ordnance_02", label = "FMMC_DPR_ORDNAN" },
			{ model = "prop_storagetank_02b", label = "FMMC_DPR_TKRDEX" },
			{ model = "prop_logpile_01", label = "FMMC_DPR_LGPLEL" },
			{ model = "prop_logpile_03", label = "FMMC_DPR_LGPLES" },
			{ model = "prop_pipes_02b", label = "FMMC_DPR_PIPPLE" },
			{ model = "prop_barrel_pile_01", label = "FMMC_DPR_BRLPLE" },
			{ model = "prop_barrel_exp_01a", label = "FMMC_DPR_EXPBRL" },
			{ model = "prop_barrel_exp_01b", label = "FMMC_DPR_BRGOEX" },
			{ model = "prop_barrel_exp_01c", label = "FMMC_DPR_BRFLEX" },
			{ model = "prop_gas_tank_01a" },
			{ model = "prop_gas_tank_02a", label = "FMMC_DPR_TKLRGW" },
			{ model = "prop_gas_tank_04a", label = "FMMC_DPR_TKLRGG" },
			{ model = "prop_gas_tank_02b", label = "FMMC_DPR_TKLRGY" },
			{ model = "prop_jerrycan_01a", label = "FMMC_DPR_JRYCAN" },
			{ model = "prop_gascyl_01a", label = "FMMC_DPR_SGC" },
			{ model = "prop_gascyl_03a", label = "FMMC_DPR_TBGAS" },
			{ model = "prop_gascyl_03b", label = "FMMC_DPR_TRGAS" },
			{ model = "prop_gascyl_02a", label = "FMMC_DPR_OLGAS" },
			{ model = "prop_gascyl_02b", label = "FMMC_DPR_OSGAS" },
			{ model = "prop_fruitstand_b", label = "FMMC_DPR_FSTND" },
			{ model = "prop_rub_tyre_03", label = "FMMC_DPR_RBRTYR" },
			{ model = "stt_prop_stunt_bowling_pin", label = "MC_PR_STNT63" },
			{ model = "stt_prop_stunt_bowling_ball", label = "MC_PR_STNT261" },
			{ model = "stt_prop_stunt_soccer_sball", label = "MC_PR_STNT66" },
			{ model = "stt_prop_stunt_soccer_ball", label = "MC_PR_STNT68" },
			{ model = "stt_prop_stunt_soccer_lball", label = "MC_PR_STNT65" },
			{ model = "imp_prop_impexp_boxpile_01", label = "FMMC_PR_92" },
			{ model = "imp_prop_groupbarrel_01", label = "FMMC_PR_94" },
			{ model = "imp_prop_groupbarrel_02", label = "FMMC_PR_95" },
			{ model = "imp_prop_groupbarrel_03", label = "FMMC_PR_96" },
			{ model = "sr_prop_sr_boxpile_02", label = "FMMC_PR_111" },
			{ model = "sr_prop_sr_boxpile_03", label = "FMMC_PR_112" },
			{ model = "sr_prop_sr_track_wall", label = "FMMC_PR_114" },
			{ model = "sr_prop_sr_tube_wall", label = "FMMC_PR_115" },
			{ model = "sr_mp_spec_races_ammu_sign", label = "FMMC_PR_116" },
		},
	},
	{
		name = "whatever",
		props = {
			{ model = "prop_ld_alarm_01", label = "FMMC_PR_ALARM" },
			{ model = "prop_barrier_work05", label = "FMMC_PR_PBARR" },
			{ model = "ind_prop_dlc_flag_02", label = "FMMC_PR_AMFLG" },
			{ model = "prop_flare_01", label = "FMMC_PR_FLARE" },
			{ model = "hei_prop_bank_plug", label = "FMMC_PR_BPLUG" },
			{ model = "hei_prop_wall_alarm_on", label = "FMMC_PR_AMLG1" },
			{ model = "hei_prop_wall_alarm_off", label = "FMMC_PR_AMLG2" },
			{ model = "hei_prop_hei_cash_trolly_03", label = "FMMC_PR_CASHT" },
			{ model = "hei_prop_carrier_docklight_01", label = "FMMC_PR_CARL2" },
			{ model = "hei_prop_carrier_docklight_02", label = "FMMC_PR_CARL5" },
			{ model = "hei_prop_wall_light_10a_cr", label = "FMMC_PR_WALLL" },
			{ model = "hei_prop_heist_apecrate", label = "FMMC_PR_MNKCR" },
			{ model = "hei_prop_cc_metalcover_01", label = "FMMC_PR_METCV" },
			{ model = "hei_prop_bank_alarm_01", label = "FMMC_PR_BNKAL" },
			{ model = "prop_road_memorial_02", label = "FMMC_PR_RDMEM" },
			{ model = "prop_boombox_01", label = "FMMC_PR_BBRE" },
			{ model = "prop_ghettoblast_02", label = "FMMC_PR_GHBL" },
			{ model = "prop_tapeplayer_01", label = "FMMC_PR_TAPL" },
			{ model = "prop_radio_01", label = "FMMC_PR_RADI" },
			{ model = "prop_shamal_crash", label = "FMMC_PR_89" },
			{ model = "apa_mp_apa_crashed_usaf_01a", label = "FMMC_PR_90" },
			{ model = "ind_prop_firework_01", label = "FMMC_PR_FRWK" },
			{ model = "prop_ibi_02", label = "FMMC_PR_91" },
			{ model = "bkr_prop_mast_01a", label = "FMMC_PR_ARMS" },
			{ model = "sr_prop_spec_target_s_01a", label = "FMMC_PR_BJT1" },
			{ model = "sr_prop_spec_target_m_01a", label = "FMMC_PR_BJT2" },
			{ model = "sr_prop_spec_target_b_01a", label = "FMMC_PR_BJT3" },
			{ model = "w_ar_railgun", label = "FMMC_STR_WP_52" },
		},
	},
}
_var.props.colors = {
	{
		labels = { "MC_STNT_USA", "MC_STNT_RED", "MC_STNT_BLU", "MC_STNT_PRP", "MC_STNT_BLK", "MC_STNT_WHT", "MC_STNT_GRY", "MC_STNT_YLW", "MC_STNT_ORG", "MC_STNT_GRN", "MC_STNT_PNK", "MC_STNT_RAC", "MC_STNT_BNY", "MC_STNT_ONB", "MC_STNT_GNY", "MC_STNT_PNG" },
		models = {
			"stt_prop_track_start",
			"stt_prop_track_start_02",
			"stt_prop_track_straight_s",
			"stt_prop_track_straight_m",
			"stt_prop_track_straight_lm",
			"stt_prop_track_straight_l",
			"stt_prop_track_bend_m",
			"stt_prop_track_bend_l",
			"stt_prop_track_bend2_l",
			"stt_prop_track_bend_5d",
			"stt_prop_track_bend_15d",
			"stt_prop_track_bend_30d",
			"stt_prop_track_bend_180d",
			"stt_prop_track_fork",
			"stt_prop_track_cross",
			"stt_prop_track_straight_bar_s",
			"stt_prop_track_straight_bar_m",
			"stt_prop_track_straight_lm_bar",
			"stt_prop_track_straight_bar_l",
			"stt_prop_track_bend_bar_m",
			"stt_prop_track_bend_bar_l",
			"stt_prop_track_bend2_bar_l",
			"stt_prop_track_bend_5d_bar",
			"stt_prop_track_bend_15d_bar",
			"stt_prop_track_bend_30d_bar",
			"stt_prop_track_bend_180d_bar",
			"stt_prop_track_fork_bar",
			"stt_prop_track_cross_bar",
			"stt_prop_track_funnel",
			"stt_prop_track_funnel_ads_01a",
			"stt_prop_track_funnel_ads_01b",
			"stt_prop_track_funnel_ads_01c",
			"stt_prop_track_link",
			"stt_prop_track_chicane_l",
			"stt_prop_track_chicane_r",
			"stt_prop_track_chicane_l_02",
			"stt_prop_track_chicane_r_02",
			"stt_prop_race_start_line_01",
			"stt_prop_race_start_line_01b",
			-740259979,
			"stt_prop_race_start_line_02b",
			"stt_prop_race_start_line_03",
			"stt_prop_race_start_line_03b",
			"stt_prop_track_block_03",
			901501250,
			-297099405,
			"stt_prop_track_bend_bar_l_b",
			"stt_prop_track_bend2_bar_l_b",
			"stt_prop_track_bend_l_b",
			"stt_prop_track_bend2_l_b",
			"stt_prop_track_block_01",
			"stt_prop_track_block_02",
			346118110,
			1486974596,
			-863549590,
			-1202280195,
			-1834664202,
			-763509440,
			-2065716143,
			-921193496,
			"stt_prop_stunt_tube_xxs",
			-38230983,
			"stt_prop_stunt_tube_xs",
			-46524906,
			"stt_prop_stunt_tube_s",
			1060884015,
			"stt_prop_stunt_tube_m",
			-794398462,
			"stt_prop_stunt_tube_l",
			-1009985713,
			"stt_prop_stunt_tube_crn",
			-1495513247,
			"stt_prop_stunt_tube_crn_5d",
			"stt_prop_stunt_tube_crn_15d",
			"stt_prop_stunt_tube_crn_30d",
			"stt_prop_stunt_tube_crn2",
			-812083680,
			"stt_prop_stunt_tube_fork",
			"stt_prop_stunt_tube_cross",
			-1951016952,
			"stt_prop_stunt_tube_gap_01",
			564151899,
			"stt_prop_stunt_tube_gap_02",
			710268902,
			"stt_prop_stunt_tube_gap_03",
			1534868018,
			"stt_prop_stunt_tube_qg",
			"stt_prop_stunt_tube_hg",
			"stt_prop_stunt_tube_jmp",
			"stt_prop_stunt_tube_jmp2",
			"stt_prop_stunt_tube_fn_01",
			"stt_prop_stunt_tube_fn_02",
			"stt_prop_stunt_tube_fn_03",
			"stt_prop_stunt_tube_fn_04",
			"stt_prop_stunt_tube_fn_05",
			"stt_prop_stunt_tube_ent",
			"stt_prop_stunt_tube_end",
			658053636,
			"stt_prop_track_tube_01",
			"stt_prop_tyre_wall_01",
			"stt_prop_tyre_wall_02",
			"stt_prop_tyre_wall_03",
			"stt_prop_tyre_wall_04",
			"stt_prop_tyre_wall_05",
			"stt_prop_tyre_wall_06",
			"stt_prop_tyre_wall_07",
			"stt_prop_tyre_wall_08",
			"stt_prop_tyre_wall_09",
			"stt_prop_tyre_wall_010",
			"stt_prop_tyre_wall_011",
			"stt_prop_tyre_wall_012",
			"stt_prop_tyre_wall_013",
			"stt_prop_tyre_wall_014",
			"stt_prop_tyre_wall_015",
			"stt_prop_tyre_wall_0r1",
			"stt_prop_tyre_wall_0r2",
			"stt_prop_tyre_wall_0r3",
			"stt_prop_tyre_wall_0r04",
			"stt_prop_tyre_wall_0r05",
			"stt_prop_tyre_wall_0r06",
			"stt_prop_tyre_wall_0r07",
			"stt_prop_tyre_wall_0r08",
			"stt_prop_tyre_wall_0r09",
			"stt_prop_tyre_wall_0r010",
			"stt_prop_tyre_wall_0r011",
			"stt_prop_tyre_wall_0r012",
			"stt_prop_tyre_wall_0r013",
			"stt_prop_tyre_wall_0r014",
			"stt_prop_tyre_wall_0r015",
			"stt_prop_tyre_wall_0r016",
			"stt_prop_tyre_wall_0r017",
			"stt_prop_tyre_wall_0r018",
			"stt_prop_tyre_wall_0r019",
			"stt_prop_tyre_wall_0l1",
			"stt_prop_tyre_wall_0l2",
			"stt_prop_tyre_wall_0l3",
			"stt_prop_tyre_wall_0l04",
			"stt_prop_tyre_wall_0l05",
			"stt_prop_tyre_wall_0l06",
			"stt_prop_tyre_wall_0l07",
			"stt_prop_tyre_wall_0l08",
			1784795865,
			"stt_prop_tyre_wall_0l010",
			1307595665,
			"stt_prop_tyre_wall_0l012",
			"stt_prop_tyre_wall_0l013",
			"stt_prop_tyre_wall_0l014",
			"stt_prop_tyre_wall_0l015",
			"stt_prop_tyre_wall_0l16",
			"stt_prop_tyre_wall_0l17",
			"stt_prop_tyre_wall_0l018",
			"stt_prop_tyre_wall_0l019",
			"stt_prop_tyre_wall_0l020",
			"stt_prop_track_stop_sign",
			"stt_prop_stunt_target_small",
			"stt_prop_stunt_target",
			"stt_prop_stunt_bowlpin_stand",
			"stt_prop_stunt_landing_zone_01",
			"stt_prop_hoop_tyre_01a",
			"stt_prop_stunt_bblock_sml1",
			"stt_prop_stunt_bblock_sml2",
			"stt_prop_stunt_bblock_sml3",
			"stt_prop_stunt_bblock_mdm1",
			"stt_prop_stunt_bblock_mdm2",
			"stt_prop_stunt_bblock_mdm3",
			"stt_prop_stunt_bblock_lrg1",
			"stt_prop_stunt_bblock_lrg2",
			"stt_prop_stunt_bblock_lrg3",
			"stt_prop_stunt_bblock_xl1",
			"stt_prop_stunt_bblock_xl2",
			"stt_prop_stunt_bblock_xl3",
			"stt_prop_stunt_bblock_huge_01",
			"stt_prop_stunt_bblock_huge_02",
			"stt_prop_stunt_bblock_huge_03",
			"stt_prop_stunt_bblock_huge_04",
			"stt_prop_stunt_bblock_huge_05",
			"stt_prop_stunt_bowling_ball",
			1390188982,
			"stt_prop_stunt_soccer_goal",
			"stt_prop_stunt_track_start",
			"stt_prop_stunt_track_start_02",
			"stt_prop_stunt_track_st_01",
			"stt_prop_stunt_track_st_02",
			"stt_prop_stunt_track_exshort",
			"stt_prop_stunt_track_short",
			"stt_prop_stunt_track_straight",
			"stt_prop_stunt_track_turn",
			"stt_prop_stunt_track_sh15",
			"stt_prop_stunt_track_sh30",
			"stt_prop_stunt_track_sh45",
			"stt_prop_stunt_track_sh45_a",
			"stt_prop_stunt_track_uturn",
			"stt_prop_stunt_track_cutout",
			"stt_prop_stunt_track_otake",
			"stt_prop_stunt_track_fork",
			"stt_prop_stunt_track_funnel",
			"stt_prop_stunt_track_funlng",
			"stt_prop_stunt_track_slope15",
			"stt_prop_stunt_track_slope30",
			"stt_prop_stunt_track_slope45",
			"stt_prop_stunt_track_link",
			"stt_prop_stunt_track_dwlink",
			"stt_prop_stunt_track_dwlink_02",
			"stt_prop_stunt_track_hill",
			"stt_prop_stunt_track_hill2",
			"stt_prop_stunt_track_bumps",
			"stt_prop_stunt_track_jump",
			"stt_prop_stunt_jump15",
			"stt_prop_stunt_jump30",
			"stt_prop_stunt_jump45",
			"stt_prop_stunt_track_dwshort",
			"stt_prop_stunt_track_dwsh15",
			"stt_prop_stunt_track_dwturn",
			"stt_prop_stunt_track_dwuturn",
			"stt_prop_stunt_track_dwslope15",
			"stt_prop_stunt_track_dwslope30",
			"stt_prop_stunt_track_dwslope45",
			"stt_prop_track_tube_02",
			"stt_prop_stunt_jump_s",
			"stt_prop_stunt_jump_m",
			"stt_prop_stunt_jump_l",
			"stt_prop_stunt_jump_sb",
			"stt_prop_stunt_jump_mb",
			"stt_prop_stunt_jump_lb",
			"stt_prop_ramp_jump_xs",
			"stt_prop_ramp_jump_s",
			"stt_prop_ramp_jump_m",
			"stt_prop_ramp_jump_l",
			"stt_prop_ramp_jump_xl",
			"stt_prop_ramp_jump_xxl",
			"stt_prop_track_jump_01a",
			"stt_prop_track_jump_01b",
			"stt_prop_track_jump_01c",
			"stt_prop_track_jump_02a",
			"stt_prop_track_jump_02b",
			"stt_prop_track_jump_02c",
			"stt_prop_ramp_adj_flip_s",
			"stt_prop_ramp_adj_flip_sb",
			"stt_prop_ramp_adj_flip_m",
			"stt_prop_ramp_adj_flip_mb",
			"stt_prop_stunt_ramp",
			"stt_prop_stunt_wideramp",
			"stt_prop_stunt_bblock_qp",
			"stt_prop_stunt_bblock_qp2",
			"stt_prop_stunt_bblock_qp3",
			"stt_prop_stunt_bblock_hump_01",
			"stt_prop_stunt_bblock_hump_02",
			1522336754,
			-1376081264,
			1123013752,
			1009862996,
			-1101562359,
			563005858,
			-469285935,
			-193600338,
			260774616,
			-131993690,
			29885170,
			-931000217,
			-29366490,
			1490006141,
			2019514094,
			-1460937400,
			2131364229,
			80379378,
			-1111661991,
			-1132240923,
			"stt_prop_wallride_05",
			"stt_prop_ramp_adj_loop",
			"stt_prop_ramp_multi_loop_rb",
			"stt_prop_stunt_jump_loop",
			"stt_prop_ramp_spiral_s",
			"stt_prop_ramp_spiral_l_s",
			"stt_prop_ramp_spiral_m",
			"stt_prop_ramp_spiral_l_m",
			"stt_prop_ramp_spiral_l",
			"stt_prop_ramp_spiral_l_l",
			"stt_prop_ramp_spiral_xxl",
			"stt_prop_ramp_spiral_l_xxl",
			"stt_prop_ramp_adj_hloop",
			"stt_prop_wallride_01",
			"stt_prop_wallride_01b",
			"stt_prop_wallride_04",
			"stt_prop_wallride_45r",
			"stt_prop_wallride_45ra",
			"stt_prop_wallride_45l",
			"stt_prop_wallride_45la",
			"stt_prop_wallride_90r",
			"stt_prop_wallride_90rb",
			"stt_prop_wallride_90l",
			"stt_prop_wallride_90lb",
			"stt_prop_wallride_02",
			"stt_prop_wallride_02b",
			"stt_prop_wallride_05b",
			-630267126,
			-1344401943,
			-1137432939,
			-1751978709,
			-1524398004,
			2032545874,
			552023728,
			312351262,
			1165295563,
			1939128168,
			-2058034456,
			-1775238062,
			-411908812,
			959604918,
			-875950621,
			511619919,
			690735273,
			949515150,
			-109574202,
			-1342281820,
			1112939169,
			1575467428,
			472547144,
			362681026,
			-1398962413,
		},
	},
	{
		labels = { "MC_STNT_BLK", "MC_STNT_RED", "MC_STNT_BLU", "MC_STNT_PNK", "MC_STNT_GRY", "MC_STNT_WHT", "MC_STNT_GRY", "MC_STNT_YLW", "MC_STNT_ORG", "MC_STNT_GRN" },
		models = {
			"stt_prop_hoop_tyre_01a",
			-291659998,
			1673929480,
			1708511539,
			-117245244,
			-60015937,
			-1576755324,
			-544828600,
			-558053832,
			-796663061,
			-816612831,
			-237619225,
			1666830192,
			-838998190,
		},
	},
	{
		labels = { "MC_STNT_BNW", "MC_STNT_YNR", "MC_STNT_RNW", "MC_STNT_YNB" },
		models = {
			"stt_prop_corner_sign_01",
			"stt_prop_corner_sign_02",
			"stt_prop_corner_sign_03",
			"stt_prop_corner_sign_04",
			"stt_prop_corner_sign_05",
			"stt_prop_corner_sign_06",
			"stt_prop_corner_sign_07",
			"stt_prop_corner_sign_08",
			"stt_prop_corner_sign_09",
			"stt_prop_corner_sign_10",
			"stt_prop_corner_sign_11",
			"stt_prop_corner_sign_12",
			"stt_prop_corner_sign_13",
			"stt_prop_corner_sign_14",
		},
	},
	{
		labels = { "MC_STNT_USA", "MC_STNT_RNW", "MC_STNT_BLU", "MC_STNT_PRP", "MC_STNT_BLK", "MC_STNT_WHT", "MC_STNT_GRY", "MC_STNT_YLW", "MC_STNT_ORG", "MC_STNT_GRN", "MC_STNT_GNP", "MC_STNT_RAC", "MC_STNT_BNY", "MC_STNT_ONB", "MC_STNT_GNY", "MC_STNT_PNG" },
		models = {
			-731135591,
		},
	},
}
_var.peds.list = {
	"a_c_boar",
	"a_c_boar_02",
	"a_c_cat_01",
	"a_c_cat_02",
	"a_c_chickenhawk",
	"a_c_chimp",
	"a_c_chimp_02",
	"a_c_chop",
	"a_c_chop_02",
	"a_c_cormorant",
	"a_c_cow",
	"a_c_coyote",
	"a_c_coyote_02",
	"a_c_crow",
	"a_c_deer",
	"a_c_deer_02",
	"a_c_dolphin",
	"a_c_fish",
	"a_c_hen",
	"a_c_humpback",
	"a_c_husky",
	"a_c_killerwhale",
	"a_c_mtlion",
	"a_c_mtlion_02",
	"a_c_panther",
	"a_c_pig",
	"a_c_pigeon",
	"a_c_poodle",
	"a_c_pug",
	"a_c_pug_02",
	"a_c_rabbit_01",
	"a_c_rabbit_02",
	"a_c_rat",
	"a_c_retriever",
	"a_c_rhesus",
	"a_c_rottweiler",
	"a_c_rottweiler_02",
	"a_c_seagull",
	"a_c_sharkhammer",
	"a_c_sharktiger",
	"a_c_shepherd",
	"a_c_stingray",
	"a_c_westy",
	"a_f_m_beach_01",
	"a_f_m_bevhills_01",
	"a_f_m_bevhills_02",
	"a_f_m_bodybuild_01",
	"a_f_m_business_02",
	"a_f_m_downtown_01",
	"a_f_m_eastsa_01",
	"a_f_m_eastsa_02",
	"a_f_m_fatbla_01",
	"a_f_m_fatcult_01",
	"a_f_m_fatwhite_01",
	"a_f_m_genbiker_01",
	"a_f_m_genstreet_01",
	"a_f_m_ktown_01",
	"a_f_m_ktown_02",
	"a_f_m_prolhost_01",
	"a_f_m_salton_01",
	"a_f_m_skidrow_01",
	"a_f_m_soucent_01",
	"a_f_m_soucent_02",
	"a_f_m_soucentmc_01",
	"a_f_m_tourist_01",
	"a_f_m_tramp_01",
	"a_f_m_trampbeac_01",
	"a_f_o_genstreet_01",
	"a_f_o_indian_01",
	"a_f_o_ktown_01",
	"a_f_o_salton_01",
	"a_f_o_soucent_01",
	"a_f_o_soucent_02",
	"a_f_y_beach_01",
	"a_f_y_beach_02",
	"a_f_y_bevhills_01",
	"a_f_y_bevhills_02",
	"a_f_y_bevhills_03",
	"a_f_y_bevhills_04",
	"a_f_y_bevhills_05",
	"a_f_y_business_01",
	"a_f_y_business_02",
	"a_f_y_business_03",
	"a_f_y_business_04",
	"a_f_y_carclub_01",
	"a_f_y_carclub_02",
	"a_f_y_clubcust_01",
	"a_f_y_clubcust_02",
	"a_f_y_clubcust_03",
	"a_f_y_clubcust_04",
	"a_f_y_eastsa_01",
	"a_f_y_eastsa_02",
	"a_f_y_eastsa_03",
	"a_f_y_epsilon_01",
	"a_f_y_femaleagent",
	"a_f_y_fitness_01",
	"a_f_y_fitness_02",
	"a_f_y_gencaspat_01",
	"a_f_y_genhot_01",
	"a_f_y_golfer_01",
	"a_f_y_hiker_01",
	"a_f_y_hippie_01",
	"a_f_y_hipster_01",
	"a_f_y_hipster_02",
	"a_f_y_hipster_03",
	"a_f_y_hipster_04",
	"a_f_y_indian_01",
	"a_f_y_juggalo_01",
	"a_f_y_runner_01",
	"a_f_y_rurmeth_01",
	"a_f_y_scdressy_01",
	"a_f_y_skater_01",
	"a_f_y_smartcaspat_01",
	"a_f_y_soucent_01",
	"a_f_y_soucent_02",
	"a_f_y_soucent_03",
	"a_f_y_studioparty_01",
	"a_f_y_studioparty_02",
	"a_f_y_tennis_01",
	"a_f_y_topless_01",
	"a_f_y_tourist_01",
	"a_f_y_tourist_02",
	"a_f_y_vinewood_01",
	"a_f_y_vinewood_02",
	"a_f_y_vinewood_03",
	"a_f_y_vinewood_04",
	"a_f_y_yoga_01",
	"a_m_m_acult_01",
	"a_m_m_afriamer_01",
	"a_m_m_bankrobber_01",
	"a_m_m_beach_01",
	"a_m_m_beach_02",
	"a_m_m_bevhills_01",
	"a_m_m_bevhills_02",
	"a_m_m_business_01",
	"a_m_m_eastsa_01",
	"a_m_m_eastsa_02",
	"a_m_m_farmer_01",
	"a_m_m_fatlatin_01",
	"a_m_m_genbiker_01",
	"a_m_m_genfat_01",
	"a_m_m_genfat_02",
	"a_m_m_golfer_01",
	"a_m_m_hasjew_01",
	"a_m_m_hillbilly_01",
	"a_m_m_hillbilly_02",
	"a_m_m_indian_01",
	"a_m_m_ktown_01",
	"a_m_m_malibu_01",
	"a_m_m_mexcntry_01",
	"a_m_m_mexlabor_01",
	"a_m_m_mlcrisis_01",
	"a_m_m_og_boss_01",
	"a_m_m_paparazzi_01",
	"a_m_m_polynesian_01",
	"a_m_m_prolhost_01",
	"a_m_m_rurmeth_01",
	"a_m_m_salton_01",
	"a_m_m_salton_02",
	"a_m_m_salton_03",
	"a_m_m_salton_04",
	"a_m_m_skater_01",
	"a_m_m_skidrow_01",
	"a_m_m_socenlat_01",
	"a_m_m_soucent_01",
	"a_m_m_soucent_02",
	"a_m_m_soucent_03",
	"a_m_m_soucent_04",
	"a_m_m_stlat_02",
	"a_m_m_studioparty_01",
	"a_m_m_tennis_01",
	"a_m_m_tourist_01",
	"a_m_m_tramp_01",
	"a_m_m_trampbeac_01",
	"a_m_m_tranvest_01",
	"a_m_m_tranvest_02",
	"a_m_o_acult_01",
	"a_m_o_acult_02",
	"a_m_o_beach_01",
	"a_m_o_beach_02",
	"a_m_o_genstreet_01",
	"a_m_o_ktown_01",
	"a_m_o_salton_01",
	"a_m_o_soucent_01",
	"a_m_o_soucent_02",
	"a_m_o_soucent_03",
	"a_m_o_tramp_01",
	"a_m_y_acult_01",
	"a_m_y_acult_02",
	"a_m_y_beach_01",
	"a_m_y_beach_02",
	"a_m_y_beach_03",
	"a_m_y_beach_04",
	"a_m_y_beachvesp_01",
	"a_m_y_beachvesp_02",
	"a_m_y_bevhills_01",
	"a_m_y_bevhills_02",
	"a_m_y_breakdance_01",
	"a_m_y_busicas_01",
	"a_m_y_business_01",
	"a_m_y_business_02",
	"a_m_y_business_03",
	"a_m_y_carclub_01",
	"a_m_y_carclub_02",
	"a_m_y_clubcust_01",
	"a_m_y_clubcust_02",
	"a_m_y_clubcust_03",
	"a_m_y_clubcust_04",
	"a_m_y_cyclist_01",
	"a_m_y_dhill_01",
	"a_m_y_downtown_01",
	"a_m_y_eastsa_01",
	"a_m_y_eastsa_02",
	"a_m_y_epsilon_01",
	"a_m_y_epsilon_02",
	"a_m_y_gay_01",
	"a_m_y_gay_02",
	"a_m_y_gencaspat_01",
	"a_m_y_genstreet_01",
	"a_m_y_genstreet_02",
	"a_m_y_golfer_01",
	"a_m_y_hasjew_01",
	"a_m_y_hiker_01",
	"a_m_y_hippy_01",
	"a_m_y_hipster_01",
	"a_m_y_hipster_02",
	"a_m_y_hipster_03",
	"a_m_y_indian_01",
	"a_m_y_jetski_01",
	"a_m_y_juggalo_01",
	"a_m_y_ktown_01",
	"a_m_y_ktown_02",
	"a_m_y_latino_01",
	"a_m_y_methhead_01",
	"a_m_y_mexthug_01",
	"a_m_y_motox_01",
	"a_m_y_motox_02",
	"a_m_y_musclbeac_01",
	"a_m_y_musclbeac_02",
	"a_m_y_polynesian_01",
	"a_m_y_roadcyc_01",
	"a_m_y_runner_01",
	"a_m_y_runner_02",
	"a_m_y_salton_01",
	"a_m_y_skater_01",
	"a_m_y_skater_02",
	"a_m_y_smartcaspat_01",
	"a_m_y_soucent_01",
	"a_m_y_soucent_02",
	"a_m_y_soucent_03",
	"a_m_y_soucent_04",
	"a_m_y_stbla_01",
	"a_m_y_stbla_02",
	"a_m_y_stlat_01",
	"a_m_y_studioparty_01",
	"a_m_y_stwhi_01",
	"a_m_y_stwhi_02",
	"a_m_y_sunbathe_01",
	"a_m_y_surfer_01",
	"a_m_y_tattoocust_01",
	"a_m_y_vindouche_01",
	"a_m_y_vinewood_01",
	"a_m_y_vinewood_02",
	"a_m_y_vinewood_03",
	"a_m_y_vinewood_04",
	"a_m_y_yoga_01",
	"cs_amandatownley",
	"cs_amandatownley_02",
	"cs_andreas",
	"cs_ashley",
	"cs_bankman",
	"cs_barry",
	"cs_beverly",
	"cs_brad",
	"cs_bradcadaver",
	"cs_carbuyer",
	"cs_casey",
	"cs_chengsr",
	"cs_chrisformage",
	"cs_clay",
	"cs_dale",
	"cs_davenorton",
	"cs_debra",
	"cs_denise",
	"cs_devin",
	"cs_dom",
	"cs_dreyfuss",
	"cs_drfriedlander",
	"cs_drfriedlander_02",
	"cs_fabien",
	"cs_fbisuit_01",
	"cs_floyd",
	"cs_guadalope",
	"cs_gurk",
	"cs_hunter",
	"cs_janet",
	"cs_jewelass",
	"cs_jimmyboston",
	"cs_jimmydisanto",
	"cs_jimmydisanto2",
	"cs_joeminuteman",
	"cs_johnnyklebitz",
	"cs_josef",
	"cs_josh",
	"cs_karen_daniels",
	"cs_lamardavis",
	"cs_lamardavis_02",
	"cs_lazlow",
	"cs_lazlow_2",
	"cs_lestercrest",
	"cs_lestercrest_2",
	"cs_lestercrest_3",
	"cs_lifeinvad_01",
	"cs_magenta",
	"cs_manuel",
	"cs_marnie",
	"cs_martinmadrazo",
	"cs_martinmadrazo_02",
	"cs_maryann",
	"cs_michelle",
	"cs_milton",
	"cs_molly",
	"cs_movpremf_01",
	"cs_movpremmale",
	"cs_mrk",
	"cs_mrs_thornhill",
	"cs_mrsphillips",
	"cs_natalia",
	"cs_nervousron",
	"cs_nervousron_02",
	"cs_nigel",
	"cs_old_man1a",
	"cs_old_man2",
	"cs_omega",
	"cs_orleans",
	"cs_paper",
	"cs_patricia",
	"cs_patricia_02",
	"cs_priest",
	"cs_prolsec_02",
	"cs_russiandrunk",
	"cs_siemonyetarian",
	"cs_solomon",
	"cs_stevehains",
	"cs_stretch",
	"cs_tanisha",
	"cs_taocheng",
	"cs_taocheng2",
	"cs_taostranslator",
	"cs_taostranslator2",
	"cs_tenniscoach",
	"cs_terry",
	"cs_tom",
	"cs_tomepsilon",
	"cs_tracydisanto",
	"cs_wade",
	"cs_zimbor",
	"csb_abigail",
	"csb_agatha",
	"csb_agent",
	"csb_agent14_02",
	"csb_alan",
	"csb_anita",
	"csb_anton",
	"csb_ary",
	"csb_ary_02",
	"csb_avery",
	"csb_avi_04",
	"csb_avischwartzman_02",
	"csb_avischwartzman_03",
	"csb_avon",
	"csb_ballas_leader",
	"csb_ballasog",
	"csb_billionaire",
	"csb_bogdan",
	"csb_bride",
	"csb_brucie2",
	"csb_bryony",
	"csb_burgerdrug",
	"csb_callgirl_01",
	"csb_callgirl_02",
	"csb_car3guy1",
	"csb_car3guy2",
	"csb_celeb_01",
	"csb_charlie_reed",
	"csb_chef",
	"csb_chef2",
	"csb_chef_03",
	"csb_chin_goon",
	"csb_cletus",
	"csb_cop",
	"csb_customer",
	"csb_dax",
	"csb_denise_friend",
	"csb_dix",
	"csb_djblamadon",
	"csb_drugdealer",
	"csb_englishdave",
	"csb_englishdave_02",
	"csb_faber_02",
	"csb_fos_rep",
	"csb_g",
	"csb_georginacheng",
	"csb_golfer_a",
	"csb_golfer_b",
	"csb_groom",
	"csb_grove_str_dlr",
	"csb_gustavo",
	"csb_hao",
	"csb_hao_02",
	"csb_helmsmanpavel",
	"csb_helmsmanpavel_02",
	"csb_huang",
	"csb_hugh",
	"csb_imani",
	"csb_imran",
	"csb_isldj_00",
	"csb_isldj_01",
	"csb_isldj_02",
	"csb_isldj_03",
	"csb_isldj_04",
	"csb_jackhowitzer",
	"csb_jamalamir",
	"csb_janitor",
	"csb_jenettee",
	"csb_jio",
	"csb_jio_02",
	"csb_jodimarshall",
	"csb_johnny_guns",
	"csb_juanstrickler",
	"csb_labrat",
	"csb_luchadora",
	"csb_maude",
	"csb_maude_02",
	"csb_miguelmadrazo",
	"csb_mimi",
	"csb_mjo",
	"csb_mjo_02",
	"csb_money",
	"csb_moodyman_02",
	"csb_mp_agent14",
	"csb_mrs_r",
	"csb_musician_00",
	"csb_mweather",
	"csb_ortega",
	"csb_oscar",
	"csb_oscar_02",
	"csb_paige",
	"csb_party_promo",
	"csb_popov",
	"csb_porndudes",
	"csb_prologuedriver",
	"csb_prolsec",
	"csb_rafdeangelis",
	"csb_ramp_gang",
	"csb_ramp_hic",
	"csb_ramp_hipster",
	"csb_ramp_marine",
	"csb_ramp_mex",
	"csb_rashcosvki",
	"csb_reporter",
	"csb_req_officer",
	"csb_roccopelosi",
	"csb_screen_writer",
	"csb_security_a",
	"csb_sessanta",
	"csb_sol",
	"csb_soundeng_00",
	"csb_sss",
	"csb_stripper_01",
	"csb_stripper_02",
	"csb_talcc",
	"csb_talmm",
	"csb_thornton",
	"csb_tomcasino",
	"csb_tonya",
	"csb_tonyprince",
	"csb_trafficwarden",
	"csb_undercover",
	"csb_vagos_leader",
	"csb_vagspeak",
	"csb_valentina",
	"csb_vernon",
	"csb_vincent",
	"csb_vincent_2",
	"csb_vincent_4",
	"csb_weiss",
	"csb_wendy",
	"csb_yusufamir",
	"g_f_importexport_01",
	"g_f_m_fooliganz_01",
	"g_f_m_undeadmage",
	"g_f_y_ballas_01",
	"g_f_y_families_01",
	"g_f_y_lost_01",
	"g_f_y_vagos_01",
	"g_m_importexport_01",
	"g_m_m_armboss_01",
	"g_m_m_armgoon_01",
	"g_m_m_armlieut_01",
	"g_m_m_cartelgoons_01",
	"g_m_m_cartelguards_01",
	"g_m_m_cartelguards_02",
	"g_m_m_casrn_01",
	"g_m_m_chemwork_01",
	"g_m_m_chiboss_01",
	"g_m_m_chicold_01",
	"g_m_m_chigoon_01",
	"g_m_m_chigoon_02",
	"g_m_m_fooliganz_01",
	"g_m_m_friedlandergoons_01",
	"g_m_m_genthug_01",
	"g_m_m_goons_01",
	"g_m_m_knoway_01",
	"g_m_m_korboss_01",
	"g_m_m_maragrande_01",
	"g_m_m_mexboss_01",
	"g_m_m_mexboss_02",
	"g_m_m_prisoners_01",
	"g_m_m_slasher_01",
	"g_m_m_zombie_01",
	"g_m_m_zombie_02",
	"g_m_m_zombie_03",
	"g_m_m_zombie_04",
	"g_m_m_zombie_05",
	"g_m_y_armgoon_02",
	"g_m_y_azteca_01",
	"g_m_y_ballaeast_01",
	"g_m_y_ballaorig_01",
	"g_m_y_ballasout_01",
	"g_m_y_famca_01",
	"g_m_y_famdnf_01",
	"g_m_y_famfor_01",
	"g_m_y_korean_01",
	"g_m_y_korean_02",
	"g_m_y_korlieut_01",
	"g_m_y_lost_01",
	"g_m_y_lost_02",
	"g_m_y_lost_03",
	"g_m_y_mexgang_01",
	"g_m_y_mexgoon_01",
	"g_m_y_mexgoon_02",
	"g_m_y_mexgoon_03",
	"g_m_y_pologoon_01",
	"g_m_y_pologoon_02",
	"g_m_y_salvaboss_01",
	"g_m_y_salvagoon_01",
	"g_m_y_salvagoon_02",
	"g_m_y_salvagoon_03",
	"g_m_y_strpunk_01",
	"g_m_y_strpunk_02",
	"hc_driver",
	"hc_gunman",
	"hc_hacker",
	"ig_abigail",
	"ig_acidlabcook",
	"ig_agatha",
	"ig_agent",
	"ig_agent14_02",
	"ig_agent_02",
	"ig_ahronward",
	"ig_amandatownley",
	"ig_amandatownley_02",
	"ig_andreas",
	"ig_armsmanufac_01",
	"ig_ary",
	"ig_ary_02",
	"ig_ashley",
	"ig_avery",
	"ig_avi_04",
	"ig_avischwartzman_02",
	"ig_avischwartzman_03",
	"ig_avon",
	"ig_ballas_leader",
	"ig_ballasog",
	"ig_bankman",
	"ig_barry",
	"ig_benny",
	"ig_benny_02",
	"ig_bestmen",
	"ig_beverly",
	"ig_billionaire",
	"ig_bountytarget_01",
	"ig_bountytarget_02",
	"ig_bountytarget_03",
	"ig_bountytarget_04",
	"ig_bountytarget_05",
	"ig_bountytarget_06",
	"ig_brad",
	"ig_bride",
	"ig_brucie2",
	"ig_callgirl_01",
	"ig_callgirl_02",
	"ig_car3guy1",
	"ig_car3guy2",
	"ig_casey",
	"ig_celeb_01",
	"ig_charlie_reed",
	"ig_chef",
	"ig_chef2",
	"ig_chef_03",
	"ig_chengsr",
	"ig_chrisformage",
	"ig_clay",
	"ig_claypain",
	"ig_cletus",
	"ig_dale",
	"ig_davenorton",
	"ig_dax",
	"ig_denise",
	"ig_devin",
	"ig_dix",
	"ig_djblamadon",
	"ig_djblamrupert",
	"ig_djblamryanh",
	"ig_djblamryans",
	"ig_djdixmanager",
	"ig_djgeneric_01",
	"ig_djsolfotios",
	"ig_djsoljakob",
	"ig_djsolmanager",
	"ig_djsolmike",
	"ig_djsolrobt",
	"ig_djtalaurelia",
	"ig_djtalignazio",
	"ig_dom",
	"ig_dreyfuss",
	"ig_drfriedlander",
	"ig_drfriedlander_02",
	"ig_drugdealer",
	"ig_englishdave",
	"ig_englishdave_02",
	"ig_entourage_a",
	"ig_entourage_b",
	"ig_faber_02",
	"ig_fabien",
	"ig_fbisuit_01",
	"ig_fibleader_01",
	"ig_floyd",
	"ig_fooliganz_01",
	"ig_fooliganz_02",
	"ig_furry",
	"ig_g",
	"ig_georginacheng",
	"ig_golfer_a",
	"ig_golfer_b",
	"ig_groom",
	"ig_guadalope",
	"ig_gunvanseller",
	"ig_gustavo",
	"ig_gustavo_02",
	"ig_hao",
	"ig_hao_02",
	"ig_helmsmanpavel",
	"ig_helmsmanpavel_02",
	"ig_hippyleader",
	"ig_huang",
	"ig_hunter",
	"ig_imani",
	"ig_isldj_00",
	"ig_isldj_01",
	"ig_isldj_02",
	"ig_isldj_03",
	"ig_isldj_04",
	"ig_isldj_04_d_01",
	"ig_isldj_04_d_02",
	"ig_isldj_04_e_01",
	"ig_jackie",
	"ig_jamalamir",
	"ig_janet",
	"ig_jay_norris",
	"ig_jaywalker",
	"ig_jenettee",
	"ig_jewelass",
	"ig_jimmyboston",
	"ig_jimmyboston_02",
	"ig_jimmydisanto",
	"ig_jimmydisanto2",
	"ig_jio",
	"ig_jio_02",
	"ig_jodimarshall",
	"ig_joeminuteman",
	"ig_johnny_guns",
	"ig_johnnyklebitz",
	"ig_josef",
	"ig_josh",
	"ig_juanstrickler",
	"ig_karen_daniels",
	"ig_kaylee",
	"ig_kerrymcintosh",
	"ig_kerrymcintosh_02",
	"ig_labrat",
	"ig_lacey_jones_02",
	"ig_lamardavis",
	"ig_lamardavis_02",
	"ig_lazlow",
	"ig_lazlow_2",
	"ig_lestercrest",
	"ig_lestercrest_2",
	"ig_lestercrest_3",
	"ig_lifeinvad_01",
	"ig_lifeinvad_02",
	"ig_lildee",
	"ig_luchadora",
	"ig_madrazodriver_01",
	"ig_magenta",
	"ig_malc",
	"ig_manuel",
	"ig_marnie",
	"ig_martinmadrazo_02",
	"ig_maryann",
	"ig_mason_duggan",
	"ig_maude",
	"ig_maudebf",
	"ig_mechanic_01",
	"ig_mechanic_02",
	"ig_mechanic_03",
	"ig_michelle",
	"ig_miguelmadrazo",
	"ig_milton",
	"ig_mimi",
	"ig_mjo",
	"ig_mjo_02",
	"ig_molly",
	"ig_money",
	"ig_moodyman_02",
	"ig_mp_agent14",
	"ig_mrk",
	"ig_mrs_thornhill",
	"ig_mrsphillips",
	"ig_musician_00",
	"ig_natalia",
	"ig_nervousron",
	"ig_nervousron_02",
	"ig_nigel",
	"ig_old_man1a",
	"ig_old_man2",
	"ig_oldrichguy",
	"ig_omega",
	"ig_oneil",
	"ig_orleans",
	"ig_ortega",
	"ig_oscar_02",
	"ig_paige",
	"ig_paper",
	"ig_party_promo",
	"ig_patricia",
	"ig_patricia_02",
	"ig_pernell_moss",
	"ig_pilot",
	"ig_pilot_02",
	"ig_popov",
	"ig_priest",
	"ig_prolsec_02",
	"ig_rafdeangelis",
	"ig_ramp_gang",
	"ig_ramp_hic",
	"ig_ramp_hipster",
	"ig_ramp_mex",
	"ig_rashcosvki",
	"ig_req_officer",
	"ig_roccopelosi",
	"ig_roostermccraw",
	"ig_russiandrunk",
	"ig_sacha",
	"ig_screen_writer",
	"ig_security_a",
	"ig_sessanta",
	"ig_siemonyetarian",
	"ig_skeleton_01",
	"ig_sol",
	"ig_solomon",
	"ig_soundeng_00",
	"ig_sss",
	"ig_stevehains",
	"ig_stretch",
	"ig_subcrewhead",
	"ig_talcc",
	"ig_talina",
	"ig_talmm",
	"ig_tanisha",
	"ig_taocheng",
	"ig_taocheng2",
	"ig_taostranslator",
	"ig_taostranslator2",
	"ig_tenniscoach",
	"ig_terry",
	"ig_thornton",
	"ig_tomcasino",
	"ig_tomepsilon",
	"ig_tonya",
	"ig_tonyprince",
	"ig_tracydisanto",
	"ig_trafficwarden",
	"ig_tylerdix",
	"ig_tylerdix_02",
	"ig_vagos_leader",
	"ig_vagspeak",
	"ig_valencheat",
	"ig_valentina",
	"ig_vernon",
	"ig_vincent",
	"ig_vincent_2",
	"ig_vincent_3",
	"ig_vincent_4",
	"ig_wade",
	"ig_warehouseboss",
	"ig_weiss",
	"ig_wendy",
	"ig_yusufamir",
	"ig_zimbor",
	"ig_zombie_dj_01",
	"mp_f_bennymech_01",
	"mp_f_boatstaff_01",
	"mp_f_cardesign_01",
	"mp_f_chbar_01",
	"mp_f_cocaine_01",
	"mp_f_counterfeit_01",
	"mp_f_deadhooker",
	"mp_f_execpa_01",
	"mp_f_execpa_02",
	"mp_f_forgery_01",
	"mp_f_freemode_01",
	"mp_f_helistaff_01",
	"mp_f_meth_01",
	"mp_f_misty_01",
	"mp_f_stripperlite",
	"mp_f_weed_01",
	"mp_g_m_pros_01",
	"mp_headtargets",
	"mp_m_avongoon",
	"mp_m_boatstaff_01",
	"mp_m_bogdangoon",
	"mp_m_claude_01",
	"mp_m_cocaine_01",
	"mp_m_counterfeit_01",
	"mp_m_exarmy_01",
	"mp_m_execpa_01",
	"mp_m_famdd_01",
	"mp_m_fibsec_01",
	"mp_m_forgery_01",
	"mp_m_freemode_01",
	"mp_m_g_vagfun_01",
	"mp_m_marston_01",
	"mp_m_meth_01",
	"mp_m_niko_01",
	"mp_m_securoguard_01",
	"mp_m_shopkeep_01",
	"mp_m_waremech_01",
	"mp_m_weapexp_01",
	"mp_m_weapwork_01",
	"mp_m_weed_01",
	"mp_s_m_armoured_01",
	"p_franklin_02",
	"p_michael_02",
	"player_one",
	"player_two",
	"player_zero",
	"s_f_m_autoshop_01",
	"s_f_m_fembarber",
	"s_f_m_maid_01",
	"s_f_m_retailstaff_01",
	"s_f_m_shop_high",
	"s_f_m_studioassist_01",
	"s_f_m_sweatshop_01",
	"s_f_m_warehouse_01",
	"s_f_y_airhostess_01",
	"s_f_y_bartender_01",
	"s_f_y_baywatch_01",
	"s_f_y_beachbarstaff_01",
	"s_f_y_casino_01",
	"s_f_y_clubbar_01",
	"s_f_y_clubbar_02",
	"s_f_y_cop_01",
	"s_f_y_factory_01",
	"s_f_y_hooker_01",
	"s_f_y_hooker_02",
	"s_f_y_hooker_03",
	"s_f_y_migrant_01",
	"s_f_y_movprem_01",
	"s_f_y_ranger_01",
	"s_f_y_scrubs_01",
	"s_f_y_sheriff_01",
	"s_f_y_shop_low",
	"s_f_y_shop_mid",
	"s_f_y_stripper_01",
	"s_f_y_stripper_02",
	"s_f_y_stripperlite",
	"s_f_y_sweatshop_01",
	"s_m_m_ammucountry",
	"s_m_m_armoured_01",
	"s_m_m_armoured_02",
	"s_m_m_autoshop_01",
	"s_m_m_autoshop_02",
	"s_m_m_autoshop_03",
	"s_m_m_bailoffice_01",
	"s_m_m_bouncer_01",
	"s_m_m_bouncer_02",
	"s_m_m_ccrew_01",
	"s_m_m_ccrew_02",
	"s_m_m_ccrew_03",
	"s_m_m_chemsec_01",
	"s_m_m_ciasec_01",
	"s_m_m_cntrybar_01",
	"s_m_m_cop_01",
	"s_m_m_dockwork_01",
	"s_m_m_doctor_01",
	"s_m_m_drugprocess_01",
	"s_m_m_fiboffice_01",
	"s_m_m_fiboffice_02",
	"s_m_m_fibsec_01",
	"s_m_m_fieldworker_01",
	"s_m_m_gaffer_01",
	"s_m_m_gardener_01",
	"s_m_m_gentransport",
	"s_m_m_hairdress_01",
	"s_m_m_hazmatworker_01",
	"s_m_m_highsec_01",
	"s_m_m_highsec_02",
	"s_m_m_highsec_03",
	"s_m_m_highsec_04",
	"s_m_m_highsec_05",
	"s_m_m_highsec_06",
	"s_m_m_janitor",
	"s_m_m_lathandy_01",
	"s_m_m_lifeinvad_01",
	"s_m_m_linecook",
	"s_m_m_lsmetro_01",
	"s_m_m_mariachi_01",
	"s_m_m_marine_01",
	"s_m_m_marine_02",
	"s_m_m_migrant_01",
	"s_m_m_movalien_01",
	"s_m_m_movprem_01",
	"s_m_m_movspace_01",
	"s_m_m_paramedic_01",
	"s_m_m_pilot_01",
	"s_m_m_pilot_02",
	"s_m_m_postal_01",
	"s_m_m_postal_02",
	"s_m_m_prisguard_01",
	"s_m_m_raceorg_01",
	"s_m_m_scientist_01",
	"s_m_m_security_01",
	"s_m_m_snowcop_01",
	"s_m_m_strperf_01",
	"s_m_m_strpreach_01",
	"s_m_m_strvend_01",
	"s_m_m_studioassist_02",
	"s_m_m_studioprod_01",
	"s_m_m_studiosoueng_02",
	"s_m_m_subcrew_01",
	"s_m_m_tattoo_01",
	"s_m_m_trucker_01",
	"s_m_m_ups_01",
	"s_m_m_ups_02",
	"s_m_m_warehouse_01",
	"s_m_o_busker_01",
	"s_m_y_airworker",
	"s_m_y_ammucity_01",
	"s_m_y_armymech_01",
	"s_m_y_autopsy_01",
	"s_m_y_barman_01",
	"s_m_y_baywatch_01",
	"s_m_y_blackops_01",
	"s_m_y_blackops_02",
	"s_m_y_blackops_03",
	"s_m_y_busboy_01",
	"s_m_y_casino_01",
	"s_m_y_chef_01",
	"s_m_y_clown_01",
	"s_m_y_clubbar_01",
	"s_m_y_construct_01",
	"s_m_y_construct_02",
	"s_m_y_cop_01",
	"s_m_y_dealer_01",
	"s_m_y_devinsec_01",
	"s_m_y_dockwork_01",
	"s_m_y_doorman_01",
	"s_m_y_dwservice_01",
	"s_m_y_dwservice_02",
	"s_m_y_factory_01",
	"s_m_y_fireman_01",
	"s_m_y_garbage",
	"s_m_y_grip_01",
	"s_m_y_hwaycop_01",
	"s_m_y_marine_01",
	"s_m_y_marine_02",
	"s_m_y_marine_03",
	"s_m_y_mime",
	"s_m_y_pestcont_01",
	"s_m_y_pilot_01",
	"s_m_y_prismuscl_01",
	"s_m_y_prisoner_01",
	"s_m_y_ranger_01",
	"s_m_y_robber_01",
	"s_m_y_sheriff_01",
	"s_m_y_shop_mask",
	"s_m_y_strvend_01",
	"s_m_y_swat_01",
	"s_m_y_uscg_01",
	"s_m_y_valet_01",
	"s_m_y_waiter_01",
	"s_m_y_waretech_01",
	"s_m_y_westsec_01",
	"s_m_y_westsec_02",
	"s_m_y_winclean_01",
	"s_m_y_xmech_01",
	"s_m_y_xmech_02",
	"s_m_y_xmech_02_mp",
	"slod_human",
	"slod_large_quadped",
	"slod_small_quadped",
	"u_f_m_casinocash_01",
	"u_f_m_casinoshop_01",
	"u_f_m_corpse_01",
	"u_f_m_debbie_01",
	"u_f_m_drowned_01",
	"u_f_m_miranda",
	"u_f_m_miranda_02",
	"u_f_m_promourn_01",
	"u_f_o_carol",
	"u_f_o_eileen",
	"u_f_o_moviestar",
	"u_f_o_prolhost_01",
	"u_f_y_beth",
	"u_f_y_bikerchic",
	"u_f_y_comjane",
	"u_f_y_corpse_01",
	"u_f_y_corpse_02",
	"u_f_y_danceburl_01",
	"u_f_y_dancelthr_01",
	"u_f_y_dancerave_01",
	"u_f_y_hotposh_01",
	"u_f_y_jewelass_01",
	"u_f_y_lauren",
	"u_f_y_mistress",
	"u_f_y_poppymich",
	"u_f_y_poppymich_02",
	"u_f_y_princess",
	"u_f_y_spyactress",
	"u_f_y_taylor",
	"u_m_m_aldinapoli",
	"u_m_m_bankman",
	"u_m_m_bikehire_01",
	"u_m_m_blane",
	"u_m_m_curtis",
	"u_m_m_doa_01",
	"u_m_m_edtoh",
	"u_m_m_fibarchitect",
	"u_m_m_filmdirector",
	"u_m_m_glenstank_01",
	"u_m_m_griff_01",
	"u_m_m_jesus_01",
	"u_m_m_jewelsec_01",
	"u_m_m_jewelthief",
	"u_m_m_juggernaut_03",
	"u_m_m_markfost",
	"u_m_m_partytarget",
	"u_m_m_prolsec_01",
	"u_m_m_promourn_01",
	"u_m_m_rivalpap",
	"u_m_m_spyactor",
	"u_m_m_streetart_01",
	"u_m_m_vince",
	"u_m_m_willyfist",
	"u_m_m_yeti",
	"u_m_m_yulemonster",
	"u_m_o_dean",
	"u_m_o_filmnoir",
	"u_m_o_finguru_01",
	"u_m_o_taphillbilly",
	"u_m_o_tramp_01",
	"u_m_y_abner",
	"u_m_y_antonb",
	"u_m_y_babyd",
	"u_m_y_baygor",
	"u_m_y_burgerdrug_01",
	"u_m_y_caleb",
	"u_m_y_chip",
	"u_m_y_corpse_01",
	"u_m_y_croupthief_01",
	"u_m_y_cyclist_01",
	"u_m_y_danceburl_01",
	"u_m_y_dancelthr_01",
	"u_m_y_dancerave_01",
	"u_m_y_fibmugger_01",
	"u_m_y_gabriel",
	"u_m_y_guido_01",
	"u_m_y_gunvend_01",
	"u_m_y_hippie_01",
	"u_m_y_imporage",
	"u_m_y_juggernaut_01",
	"u_m_y_juggernaut_02",
	"u_m_y_justin",
	"u_m_y_mani",
	"u_m_y_militarybum",
	"u_m_y_paparazzi",
	"u_m_y_party_01",
	"u_m_y_pogo_01",
	"u_m_y_prisoner_01",
	"u_m_y_proldriver_01",
	"u_m_y_rsranger_01",
	"u_m_y_sbike",
	"u_m_y_smugmech_01",
	"u_m_y_staggrm_01",
	"u_m_y_tattoo_01",
	"u_m_y_ushi",
	"u_m_y_zombie_01",
}
